# English lines 0-499 matching quoted_copy.json
EN1 = [
"Watch",
"Method",
"Bounds",
"Fill-in",
"Project digital copy · original not issued",
"Historical special-file digital QC workbench",
"QC workbench",
"2026 · project intranet",
"Work orders, controlled comparison, disposition advice, and project receipts",
"Internal work-order register",
"Digital QC staff",
"In use",
"Huaishui Locals",
"2004 · local BBS mirror",
"Local life, help, chatter, and old-thread archive",
"Local-user talk",
"Huaixian and nearby users",
"Read-only mirror",
"Huaixian Archives open catalog",
"Archive catalog",
"2004—2026 · several migrations",
"Look up title, date, creator, open status, and see-also files",
"Catalog-description register",
"File readers and in-house arrangers",
"Ongoing migration and errata",
"Huaibei folk holdings site",
"Folk holdings site",
"1999 · old team site",
"Field copies, local-serial index, and reader corrections",
"Hobby arrangement and desk-edit register",
"Local-culture readers and contributors",
"Old pages kept; errata hung later",
"Huaixian old-paper scan library",
"Old-paper scan library",
"1980s carriers · 2000s digitization",
"Search papers and Negatives by date, edition, and OCR body",
"Newspaper catalog and OCR-search register",
"Readers, librarians, and local-history queriers",
"Film image and OCR corrected in layers",
"NorthSlope geology library",
"Geology library",
"1992—2026 · technical files",
"Rainfall, sections, mine closure, slope, and monitoring files",
"Engineering-technical register",
"Engineering and geology file users",
"Filed by report number",
"Huaixian historical special-file digital QC project",
"Work order QA-26-0813-447",
"A NegBag marked with a homicide original-file number hung under a Landslide file for twenty-two years.",
"You are records QC-447 for this batch. The migration table was sent back; the same old index still lists AShan as SoleActor. Pull one word off the handover sheet, search the public sites, then decide whether the old title can stay in use. First word: AShan.",
"Authority: read approved digital copies, fill QC returns, submit disposition advice.",
"Sign for the work order",
"Current check",
"This item's sources",
"Return to current check",
"Save this item's return",
"Pull one word from the work-order body and search it in a public-site box. One word at a time.",
"Empty search, or two words with a space, will miss. A single token from an opened page can hit. After a hit, open that record and pull the next word.",
"The workbench form comes later. Disposition advice is only at the end; you have no approval power.",
"Anyone heard of that temple in Huaishu",
"Old talk · 1 reply · mirror has an edit log",
"OP asked about the old NorthSlope shrine. One guy talks latch, another talks IceBlock, they never land on the same thing.",
"OP: when we were kids they wouldn't let us run up NorthSlope. Grandma said the old NorthSlope still had WheelLamp and ThreeNights tally handovers, and that the bar dropped by itself that night; next door said ice was propping it and it fell when it melted.",
"Nanqiao old-timer: town used to pin it on AShan, said of the people who went down in the hall he was the one still alive, street called him Ninth. Later I even saw SoleActor on a catalog card.",
"OP edited 23:02: just saying, this is all stuff I heard as a kid. I never saw a page of the original file.",
"User memory, not a contemporaneous original file",
"Repost, the nine-people one",
"Repost board · 9 replies",
"Original link is dead. The reposter left the 'eight, plus one more' line from memory.",
"OP: orig link gone. I only remember the emergency page wrote eight first, then someone added one beside it, and after that everyone said Ninth.",
"4F: those eight, did they just reach the yard, or did they actually go into MainHall? Those columns on the old forms aren't the same thing.",
"Retelling",
"Count rule not stated",
"Could IceBlock freeze the door bar in place",
"Carpentry chatter · 24 replies",
"OP tried an ice prop on his own yard door. Replies kept asking where the meltwater would run.",
"OP: ice under the bar head, my door WILL drop. But water would run a line along the threshold. Whether the old scene even logged water, I don't know.",
"Carpenter Old Yao: don't just watch whether the bar dropped. Real ice, you'd get contact face, a drain, wood taking water — at least one of those. If the scene still had an iron pin and two strands of cord, you need a different drawing.",
"Folk structural guess",
"Cannot replace scene physical evidence",
"West-gate market, what's long beans today",
"Neighbors · 11 replies",
"A few households posted morning prices and stall spots.",
"Asked at 7:30, long beans 1.20. The row by the fish is two mao more.",
"They pack up early in the afternoon, don't waste the trip.",
"Neighbors",
"Complete",
"Where did the Nanqiao bike stall move",
"Directions · 7 replies",
"The repair stall moved to the old grain-depot wall. No stall in the rain.",
"The guy who was by the bridge is at the west wall of the grain depot now.",
"Patches still two kuai, closed Mondays.",
"Directions",
"North street out again?",
"Daily · 31 replies",
"Users reported outages and restore times by block.",
"Our side went out 21:50. County middle still had lights.",
"Power-office tape said line work, back around 23:00.",
"Daily",
"Floor-2 attachment missing",
"Class of '86 section-two reunion photos",
"Alumni · 46 replies",
"Old classmates ID people and fill names. Photos sit in upload order.",
"First shot, back row second from left, I can't swear. Don't put him on the list yet.",
"Faces alone get you the wrong guy. Wait for the homeroom roll.",
"Alumni",
"Thumbnails available",
"River-bend night fishing, water's coming up fast",
"Anglers · 14 replies",
"Anglers logged river-bend level and when they left.",
"After 22:00 it rose fast. Second paint line on the pier is almost gone.",
"Don't go to the NorthSlope foot. A ditch just punched through there.",
"Anglers",
"This file is forbidden",
"Forbidden page · no access",
"SourceCode and AdminPassword searches do not hit a record.",
"Forbidden. Go back to a page you already opened and pull one word to search.",
"Forbidden",
"Cannot replace a source check",
"2004 cataloging · 2026 QC",
"Huaishu shrine case / old-index disputed item",
"IDX-XGA98-ASHAN-2004 · catalog open",
"Historical title includes 'AShan is SoleActor'. This record is flagged for origin QC.",
"Description basis: a work sticky on the old box side. The sticky is unsigned and cites no document number.",
"Handling: old title kept for Migration check; current description status is 'pending QC'.",
"Catalog layer; does not replace file contents",
"HS-98 spine-short Migration crosswalk",
"Scan batch HS98-R07 · 4 pages",
"2004 Migration table. The same spine short lists two original files and one scan batch.",
"Original-file crosswalk: XGA-1998-0717-03→HS-98-0717; DZ-1998-0719-11→GR-98-0719.",
"Batch no. HS98-R07. Note: NegBag B's current see-also does not match the bag-tag original-file number; suspected later Overwrite; pending rehang.",
"Migration error pending correction",
"Huaishu MainHall entry record (four forms merged catalog)",
"Catalog card · images open",
"Temple handover, health-worker sign-in, introduction letters, and door register: four forms. Names were deduped by document number.",
"Merged names: ZhaoChenghai, LiuQingyu, AShan, ZhangDafu, LiYouye, ZhouShouyi, SunGuilan, LinQing. Repeat sign-ins do not start another person.",
"Field note: 'present', 'entered yard', and 'entered hall' are different columns. First full-body MainHall crossing must be QC'd line by line against the image.",
"Exit column copy: ZhaoChenghai 22:09, LiuQingyu 22:08, SunGuilan 22:07. The other five have no exit before 22:10.",
"List does not include unregistered persons",
"Paper documents, batch 427, page-by-page scan note",
"Digitizing-batch note · public",
"Batch in on 2004-05-06, 427 volumes. Digital files took create-time from that day's scan environment.",
"Page counts, missing corners, and bag numbers are registered page by page and can be checked against the intake list.",
"File hash covers the scanned body; original formation date still follows the paper description.",
"County farm-machine plant staff register: LinWen",
"Open name list · same-name item",
"Born 1964, west-town address, still continuously on post after a 1996 award.",
"This LinWen is a plant employee, not the same person as the Lin eldest son missing in 1975.",
"Exclusion fields: birth year, address, continuous work history.",
"West-town Workers' Road",
"Chenjiawan move-out register catalog card",
"Civil files · catalog only",
"Records move-out date, receiving place, and receipt page count.",
"Receiving-place receipts are complete. Images are not open for privacy limits.",
"Catalog open",
"September water-station ditch patrol record",
"Water files · 12 pages",
"Silt, block points, and recheck dates by ditch segment.",
"North ditch segment 3 silt-clear finished; recheck showed no re-block.",
"The recorded responsible person only states the shift, not a personal opinion.",
"North ditch 3",
"Reading-room annual use counts",
"Housekeeping · 2 pages",
"Counts of file visits, copy pages, and reasons material could not be supplied.",
"418 visits in the year. Unsupplied items include privacy limits, not yet digitized, and not held here.",
"Open",
"1964 material · 1999 cataloged",
"NorthSlope three-household WheelLamp book and NightWatch rule",
"Base text: village private holding · variants copied as found",
"Arranged from the WheelLamp book, lamp-oil issue pages, and ditch-patrol pages. Base-text photocopy and line collation are in the attached figures.",
"Desk note: original pages do not use one character set. Transcripts keep 户, 更, and 手 as written and do not modernize them.",
"Source column: human voucher, WheelLamp book, lamp-oil issue, ditch-patrol pages. Pages are not the same height; cropped edges were not filled.",
"Last arranged: 1999-10-06. If you have a same-batch base text, mail page numbers. Oral rewrite drafts are not taken.",
"Human voucher, WheelLamp book, ditch-patrol pages",
"Does not include children or fixed personal lamp posts",
"1970—1974 Overwrite layer",
"Three-bases-one-watch entry (later text; source layer pending check)",
"Old title 'local old-custom original' has been corrected",
"This page's old title was rehung in 2026-08. Attached figures place the 1964 base text, the Overwrite version, and local scrape marks side by side.",
"Page note: the surviving piece has added strokes, scraping, and ink-color difference. To keep web thumbnails from mixing them, desk staff re-laid base text, Overwrite, and detail as three view slots.",
"Old links are not deleted, but a version erratum sits above the title. Readers who cited the old title should use version VER-FOLK-1974-2026-08.",
"Keyer's note: this page does not guess scraped-off characters. It only layers the strokes that remain.",
"Source layer pending check",
"Version record: 1974 entry source-layer erratum",
"Version history · fixed public record",
"Title changed from 'local old-custom original' to 'later text, source layer pending check'.",
"Changed: title, source-layer note, photocopy-set order. Original URL and old page are both kept.",
"Description handling: 1964 base text and 1970—1974 Overwrite layer are separate records with mutual see-also.",
"Corrector: Huaibei folk holdings site desk. If an old-title cache still shows, note the page address in mail.",
"Public",
"Local old-custom original",
"1987 collected · 2001 online",
"Short walk to the old mine behind the temple",
"Reader submission · place not survey-checked",
"A reader counted steps looking for a mine mouth behind the temple and did not carry a survey drawing.",
"Submission: north from behind the temple, over two ditches, a sealed old mouth on the lower slope. I only counted steps. No watch.",
"Editor note: direction is kept as submitted. Coordinates, elevation, and closure status: see NorthSlope geology files.",
"Oral travel note",
"No coordinates, no section",
"One ordinary tally-handover instance from the rotation book",
"Web transcript · p.14",
"After the previous hand leaves the bound at night, night-count starts from the next full 18:00—06:00 night watch.",
"4th of the 5th month 23:10 previous hand withdrew; 5th 18:00 to 6th 06:00 is first night, then on to the third.",
"The leftover evening that is not a full night watch is not counted. Page dates follow the base text; conversion table lists Gregorian separately.",
"18:00—next day 06:00",
"Not applicable",
"Dialect words: lamp-foot, add-oil, drop-watch",
"Dialect index · Huaibei slice",
"Arranges three everyday lighting and night-rotation terms.",
"'Drop-watch' in this entry means ending one night-watch shift. It is not a ritual identity.",
"Team dialect group",
"1997 collected",
"Bridge-meeting songbook catalog",
"Catalog card · audio missing",
"Lists spring bridge-meeting song titles, singers, and tape numbers.",
"Tapes are being transferred. Catalog and text abstracts are supplied for now.",
"Catalog usable",
"1989 collected",
"Three oral notes on rain-night ditch patrol",
"Work custom · 3 items",
"Villagers talk rain-night water sound, falling stone, and rotation.",
"West-ditch people say listen to water first. North-ditch people say watch stone first. Three speakers each follow their own shift. Editor did not merge the order.",
"Huaibei three villages",
"Web transcript",
"Reader correction: two same-name mountain mouths",
"Errata column",
"Reader Mr. Zhang mailed a bearing sketch showing two same-name 'old yaks' in the old text are not one place.",
"Erratum: original 'North Ridge Mouth' changed to 'East Ridge Mouth'. Check items are collection coordinates and inbound village direction. Old page kept; this note is hung at the head.",
"Corrected",
"BF-11 bridge-head Negatives whole strip and photo log",
"NegBag B · frames 11—15 · OCR not applicable",
"NegBag B frames 11—15 are joined by perforations into one strip and can be read with the same-bag photo log.",
"Catalog note: the old catalog kept only a mid-frame thumbnail. This load adds the whole strip. Frame positions were not rearranged.",
"Photo-log time is 23:44; perforations and process numbers are continuous. Distant-figure sharpness is not enough for face ID.",
"Photo log / road sign / water staff",
"Face-ID conditions not sufficient",
"Local scraps: ThreeNights tally-handover remnant line",
"Huaixian Daily p.4 · film frame 118",
"Whole-page image of 1982-06-18 p.4. Microfilm locator is frame 118.",
"The search store once read one glyph on this page as a near-shape. 2012 corrected the OCR text. The whole-page image was not replaced.",
"Read order: whole page at frame 118 first, then match that day's issue catalog and bound-volume stamp.",
"2012 correction",
"County farm-machine plant skills contest results",
"p.2 · OCR corrected",
"The plant published spring skills-contest names, first and second prizes by trade.",
"Second prize: Lin Wen, plant machine-repair group.",
"This person column only describes name and workplace. No birth year or address.",
"Human correction",
"OCR correction record no. 884",
"Correction log · body unchanged",
"Search-text near-shape correction, task 884. Image file was not regenerated.",
"Layer record: 2004 scan; 2012 OCR field fix. Image-file IDs match before and after correction.",
"three days",
"ThreeNights",
"no",
"Summer passenger timetable change",
"p.1 · notice",
"County station changed north-line first bus and rain stop points.",
"North-line first bus ten minutes earlier. In heavy rain it skips the river-bend temp stop.",
"Searchable",
"Wheat-harvest service teams go out to repair machines",
"p.2 · production",
"Reports three repair teams' routes and service points.",
"Team 1 takes the south line, team 2 stays at West Village, team 3 goes up north ditch. Point rosters were registered that day at the machine station.",
"Weekend open-air film notice",
"p.3 · culture",
"County culture hall published three screening points and rain-delay rules.",
"North-street lot Saturday 19:30; rain delays to the next clear night.",
"Lost and found: a string of warehouse keys",
"p.4 · classified",
"Keys held at the bus-station duty room. Claimant must describe the fob.",
"Evening of March 1 a string of warehouse keys was picked up in the county-station waiting room. Owner: tell duty the key count and fob shape.",
"NorthSlope abandoned-mine closure drawing and seal acceptance",
"Report BP-M92-17 · coordinates open",
"BP-M92-17 closure acceptance, with plan, long section, and seal-point recheck table.",
"Survey extract: adit end is 184 m in plan from MainHall, 26 m lower; the section between them is continuous shale.",
"Recheck column: 1998-08 no seal cracking, seepage, or abnormal settlement.",
"Continuous shale",
"NorthSlope local Landslide first report and natural conditions",
"Report BP-1998-0719 · closed",
"First report of a local Landslide on the NorthSlope old-bound segment. Filed 1998-07-19 23:41.",
"Field conditions: cumulative rain high, shale softened, slope seepage, new scour at the toe. OldTemple platform on the slope showed no displacement. Rated as natural hazard conditions sufficient.",
"Report scope: Landslide time, place, deformation, and engineering-geology conditions. No folk or personal-identity columns.",
"NorthSlope old-bound segment",
"Natural mechanism sufficient",
"OldTemple outer outline and north-wall resurvey data",
"Engineering survey · coordinate table open",
"1998-08 same-coordinate resurvey of OldTemple outer outline, inner wall lines, and wall thickness.",
"Attached figures include OldTemple outer outline, 1998 measured inner wall lines, and the numbered-room table.",
"Values must be reclosed under HX-54 / local correction on one scale. Do not measure off web preview width.",
"Outer outline / inner wall lines / wall thickness / numbered rooms",
"HX-54 / local correction",
"West Ridge well 4 monthly report",
"Groundwater · CSV open",
"Records water level, temperature, and missing days.",
"April 12 equipment service. Missing marked typed-missing. No interpolation.",
"Closed",
"County road K17 slope drainage QC",
"Engineering geology · PDF open",
"Checks cut-off ditches, anchors, and post-rain cracks.",
"Work-point extent: K17+200 to K17+640. Huaishu NorthSlope is not in this report's coordinate box.",
"Huaibei rain station third-quarter data note",
"Monitoring data · CSV open",
"States timezone, missing observations, and cumulative-rain rule.",
"Timezone is Beijing time throughout; cross-day totals start at 00:00.",
"1976 catalog",
"North-ditch borehole log catalog card",
"Metadata only · raw data not open",
"Open items: report number, survey unit, extent, and coordinate system. Depth and lithology table are not online.",
"Access status: metadata-only. Original borehole logs require a separate request under BG-CORE-76.",
"Common overlay questions: coordinates and elevation",
"How to use",
"Warns that plan nearness is not elevation or section continuity.",
"Before overlay, check coordinate system, elevation datum, file year, and extent.",
"Help",
"AS-98 restraint-device measure card",
"In-place measures of column ring, links, lock pin, and lead seal.",
"Column-ring base (2.14, 4.08), effective chain 0.86 m; lock pin and lead seal were continuous at collection.",
"Combined with chain length, column radius, and shoulder width, max reach edge is 1.43 m from base. This card is not a legal no-liability finding.",
"MainHall trace zones and drag QC",
"Two force traces, tool drop points, and ground-drag check.",
"Head action zone 1.74—2.02 m from column-ring base; neck action zone 1.61—1.88 m from base.",
"Each action zone has a displacement gap to the final body position; ground shows no continuous drag from the column; list has no extension tool.",
"Three adult autopsy narrow-field abstracts",
"ZhangDafu, LiYouye, and ZhouShouyi: three object-independent original-file fields.",
"ZhangDafu: asphyxia from neck-cord compression; do not write 'frightened self-strangle'. LiYouye: acute myocardial infarction during the conflict; no fatal trauma.",
"ZhouShouyi: blunt head injury. Three abstracts record cause-of-death fields only. None uniquely assigns an actor.",
"Asphyxia from neck-cord compression",
"Acute myocardial infarction",
"Blunt head injury",
"Eight registered persons' 23:44 whereabouts comparison",
"Places contemporaneous whereabouts of the eight registered names from the four forms side by side. Does not identify the negative figure.",
"Exit table: ZhaoChenghai left 22:09 then entered clinic continuous handling from 22:19; LiuQingyu left 22:08 then signed east dike 22:20; SunGuilan left 22:07 then on village-committee radio from 22:18.",
"AShan in ambulance-register area from 23:31; ZhangDafu, LiYouye, ZhouShouyi stayed in the scene handling chain; LinQing transferred by ambulance 23:36.",
"This table does not contain a negative-figure name and does not state that anyone entered MainHall, came from the behind-wall space, or is the same as anonymous U1.",
"Eight registered names in the four forms",
"Not identifiable",
"AV-04 waveform and dual time-signal marks",
"Digital view of transport waveform, two time-signal points, and six event segments still to be ordered.",
"The marker boxed two time signals and six event segments on the waveform. Event segments were not pre-numbered.",
"Transport drift must be calibrated with the two time-signal points; noise-floor continuity is listed on the same track.",
"AV-04 accessible transcript and event cards",
"Text-equivalent view of non-semantic sound. No speaker is labeled.",
"E1 panel open / E2 barefoot land / E3 impact / E4 lift bar / E5 close door / E6 drop slot.",
"Recorder dropped after the impact segment but kept recording; transcript only notes sound type and relative position.",
"DOOR-98-A component measure",
"Same-scale component drawing of door body, wood bar, receiving slot, guide ring, temp pin, and door gap.",
"Measure drawing keeps inner/outer sides, pivot end, slot section, and contact-point labels.",
"Read length, diameter, door gap, and opening direction on the original drawing. The page does not add a simplified sketch.",
"In-figure labels",
"Inner/outer already marked",
"Latch fiber, scratches, and list extract",
"Zoned trace record of door bar, pin neck, guide ring, door gap, and ground.",
"The record page already splits fiber contact, metal scratch, sound delay, and ground check into columns.",
"Scene list and trace drawing are two source layers; candidate-scheme fields can be ticked only after they are read together.",
"Fiber / scratch / sound / ground",
"Separate column",
"Behind-wall object formation-time card",
"Upper and lower time bounds for repair thread, medicine bag, paper, and break, each on its own.",
"Repair thread is under the 1974 ash layer; medicine-bag lot is not earlier than 1982.",
"Paper pages are on the 1998 seal list; the rescue panel-open break was still fresh at collection.",
"Behind-wall deposit and use-layer section",
"Relative order of soot, food-port wear, and object horizons.",
"Lower repair thread is earlier than the medicine-bag layer; paper sits under newer soot; the rescue break cuts all older layers.",
"The section only supports use traces across several years. It does not supply day-by-day continuous occupancy.",
"P-07 / D-03 / W-02 anonymous sample cards",
"Three sample profiles, collection positions, and custody chains side by side. No names.",
"P-07 from behind-wall board; D-03 from temp pin; W-02 from behind-wall old bandage. The three anonymous sample profiles match.",
"Each piece was bagged separately. Collector, time, and store location are continuous.",
"F-02 continuous footprints and missing-toe field",
"Route drawing of barefoot measure points, individual trait, and exit time.",
"Footprint points are one continuous number set. The left-foot individual trait repeats in each segment.",
"Route drawing uses 23:26 as the exit-record time. Bridge-head negatives are described in another bag and are not spliced into this drawing.",
"Anonymous U1 first-crossing event card",
"Side-by-side event fields: AV-04 relative order, threshold traces, and the eight-person table.",
"After panel open, continuous barefoot traces fully cross from the behind-wall threshold into MainHall; calibrated time 22:47±1.",
"The four register forms have no such anonymous entry. The event card has no name and does not connect 23:44 bridge-head M1.",
"U1 identity conjunction QC return",
"Joint check of anonymous sample, kin model, family uniqueness, and old-injury fields.",
"Check scope: anonymous person U1 identity register. Sample merge, full-sibling relation, family uniqueness, missing window, and old foot injury all pass field-consistency check.",
"Exclusion scope: BF-11 distant figure, outside-bar operation, and three adult-death acts are not inside this return's identity finding.",
"Anonymous person U1 identity register",
"BF-11 face ID / death-act assignment",
"Lin household, school, and missing-window merged catalog",
"1975 QC",
"LinQing's recorded full sibling and LinWen missing-time fields.",
"After parents' files and school records cross, LinQing has one recorded full-sibling elder brother: LinWen.",
"LinWen's last public school/household activity stops in 1975; same-name persons must be excluded separately by birth year and address.",
"MED-LW-72 old-injury clinic-card catalog",
"Contemporaneous medical fields for LinWen's left-foot old injury.",
"Patient LinWen: left second toe distal segment absent; return visit after injury.",
"This card only supplies name, year, and physical trait. It does not contain 1998 conduct records.",
"LinWen",
"Left second toe distal segment absent",
"U1 five conduct-field table",
"1998 material / 2026 QC",
"Five conduct propositions each bound to a direct source and a current status.",
"Contact and exit: behind-wall board contact—confirmed; temp-pin contact—confirmed; 23:26 exit—confirmed.",
"Conduct responsibility: outside bar drop—still unresolved; adult-death responsibility—still unresolved.",
"FangXiaohe life and last school record",
"Roll-call, transfer-form pickup, and official-whereabouts time fields.",
"Autumn 1971 last-at-school record is complete; a later village side-note writes 'moved with kin'.",
"This attachment does not contain other children's life material.",
"FangXiaohe",
"Moved with kin",
"FangXiaohe inbound-reception check",
"1971—2026 check",
"Gaps in receiving place, stub, and receipt that should match the move-out side-note.",
"Named receiving place has no same-name inbound receipt; transfer-form pickup stub exists, but the reception copy was not completed.",
"The gap only shows the reception chain did not close. It does not prove death.",
"HR-01 / FangXiaohe independent identity check",
"Age-year, left-radius old injury, and full-brother model.",
"UNIT-G14 / HR-01: about 8 years, left radius old healed deformity; 1971 floor layer.",
"Living full-brother model supports an identity link. Do not borrow dental or tibia traits.",
"Left radius old healed deformity",
"DengMei health card and last record",
"School health card, last at school, and village official whereabouts.",
"1973 school health card joins the last record; a later village side-note writes 'died of illness'.",
"This attachment does not contain FangXiaohe or XuYousheng life material.",
"DengMei",
"Died of illness",
"DengMei medical and cemetery reception check",
"1973—2026 check",
"Search results from hospital, village doctor, and cemetery reception records.",
"Hospital death register, village-doctor reception page, and public cemetery register have no matching reception.",
"Three empty records cannot yield drug, cause of death, or an actor.",
"HR-02 / DengMei independent identity check",
"Age-year, deciduous-molar treatment mark, and mother-daughter model.",
"UNIT-G16 / HR-02: about 8 years, maxillary deciduous molar has a special treatment mark; 1973 relay layer.",
"Living mother-daughter model supports an identity link. Do not borrow radius or tibia traits.",
"Maxillary deciduous molar special treatment mark",
"XuYousheng vaccine card and last record",
"Vaccine card, errand list, and official 'drowned missing' time fields.",
"A last record still sits after the 1974 vaccine card; village notice writes 'drowned missing'.",
"The errand list only proves one ordinary contact chance. It does not prove arrival at a final place.",
"XuYousheng",
"Drowned missing",
"XuYousheng river-reception check",
"1974—2026 check",
"Search of notices, downstream reception, and unnamed-child registers.",
"A contemporaneous river search notice exists; no matching unnamed-child reception is in search scope.",
"The river empty record only narrows official whereabouts. It does not prove how death occurred.",
"HR-03 / XuYousheng independent identity check",
"Age-year, right-tibia old reaction, and full-sister model.",
"UNIT-H15 / HR-03: about 8 years, right tibia old periosteal reaction; 1974 cover layer.",
"Living full-sister model supports an identity link. Do not borrow radius or dental traits.",
"Right tibia old periosteal reaction",
"UNIT-G14 anonymous unit and floor layer",
"1971 layer",
"Anonymous-unit coordinates, engineering layer, and position number. No name.",
"UNIT-G14 / HR-01 sits in the east first old-lamp range; the seal layer matches 1971 work.",
"POS-EAST-1/east post 1",
"UNIT-G16 anonymous unit and relay layer",
"1973 layer",
"UNIT-G16 / HR-02 sits in the west second old-lamp range; the relay layer matches 1973 work.",
"POS-WEST-2/west post 2",
"UNIT-H15 anonymous unit and cover layer",
"1974 layer",
"UNIT-H15 / HR-03 sits in the north third old-lamp range; the cover layer matches 1974 work.",
"POS-NORTH-3/north post 3",
"E98-O-031 guard-tally source card",
"Tally number, old notch, cord wear, in-place photo, and successive custody nodes.",
"Guard tally was independently bagged after an in-place photo in the behind-wall living layer on 1998-07-17; 2004 only scanned through the bag.",
"Tally number and old notch match the tail-voucher rubbing; 1998—2026 in/out is continuous.",
"Handover tail-voucher number and rubbing card",
"1964 / 1974 Overwrite",
"Visible fields: tail-voucher number, notch tracing, and cord-wear marks.",
"Tail voucher marked GT-74-1; half-notch faces north-east; rubbing shows old cord wear.",
"The tail voucher is a handling record attached to the human voucher. It is not a fourth independent compact object.",
"1964 NorthSlope old-bound bearing drawing",
"Original drawing of old bound line, tally-bound marks, temple doors, and bearing refs.",
"Original is a hand bearing sketch. North, scale, bound line, and two door positions keep original labels.",
"The drawing does not contain 1998 person routes; register it to the 1998 plan with shared survey points.",
"1964 NorthSlope old-bound map",
"1998 rescue plan and 23:26 exit line",
"Same-coordinate registration of the 1964 old bound line and the 1998 exit route.",
"Overlay is calibrated on two fixed wall corners and the main-door axis. Exit line joins F-02 survey points.",
"23:44 bridge-head negatives did not take part in this spatial registration. Read the crossing on the overlay.",
"Two wall corners / main-door axis",
"SRC-COV-HUMAN human-voucher source card",
"East-cabinet collection, independent bagging, scan, and current custody status.",
"Formed 1964; 1970—1974 scrape Overwrite; collected after in-place photo in 1998 MainHall east cabinet; 2004 only scanned the exhibit card.",
"2026 still in a police restricted-custody unit. Does not prove a 1974 rite was held, or who rewrote it.",
"SRC-COV-MOUNTAIN mountain-notice counterpart source card",
"In-place find in a sealed NorthSlope voucher niche and continuous pack-in.",
"Same 1964 batch; after 1974 placed in a niche by the NorthSlope bound stone; found in place during 2026 drain reinforcement.",
"Video, seal clay, removal, packing, and intake sign-off are continuous. Does not confirm who placed it or non-human reception.",
"Candidate Plan A six live-action preview",
"2026 in-story plan card",
"Independent numbers, limited question, personnel actions, return, cancel, and conclusion scope.",
"1. Numbers and purpose: three originals keep their own numbers, documents, packing, and seals; answer only limited question RQ-01; do not merge title.",
"2. People, time, place: after each custody body authorizes separately, home-agency handlers and named examiners work at independent split benches in the county joint lab, one day shift, three hours; QC-447 is not on the handler list.",
"3. Physical actions: each piece sits in an independent cell of one outer calibration fixture and does not touch the others; compare only edge micro-deformation and half-print relative position; no character fill, no paper fill, no reprint.",
"4. Removal and return: each home-agency person checks seal, opens, watches, reseals, and returns on the original chain before the day shift ends; finds then go to the named store for seal check and accession.",
"5. Cancel and rollback: cancel if any agency approval, site, condition, seal, or transport is unmet; on exception, reseal and return on the original path; do not switch to the other plan.",
"6. Conclusion scope: record only actual actions and the RQ-01 limited opinion; issue no opinion on 1974 operations, folk efficacy, child-death responsibility, or extra causation.",
"Advice only",
"Each original's custody body",
"Named handlers",
"Candidate Plan B six live-action preview",
]
print("EN1", len(EN1))
