# English lines 500-999 matching quoted_copy.json
EN2 = [
"Piece-separate protection, digital see-also, final accession, exception rollback, and unresolved bounds.",
"1. Numbers and purpose: three originals keep their own numbers and custody chains; finish protection and bounded digital see-also with minimum movement; RQ-01 stays unresolved.",
"2. People, time, place: authorized conservation staff of each current custody body work separately in their own stores on ordinary day shifts; no shared place or shared time window; QC-447 does not handle.",
"3. Physical actions: originals do not enter a shared fixture; each gets condition assessment, suitable support, and packing; keep certified images, non-destructive tests, and uniformly calibrated derived data.",
"4. Removal and accession: no cross-store move for comparison; each piece is seal-checked by its current handler; finds are seal-checked, accepted, and finally accessioned by the named store.",
"5. Exception and rollback: if any piece is abnormal, roll back on its own custody procedure; do not add original-object risk to shrink the unresolved.",
"6. Conclusion bound: finishing piece-separate protection is not proof the old compact is void, that the children were released, or that extra causation does not exist; RQ-01 stays unresolved.",
"none",
"ZhaoChenghai flood red-cord issue and temp stock",
"Two reels issued, temp stock short one reel, and material-duty fields.",
"ZhaoChenghai signed for two new flood-cord reels; next-morning temp stock first marked one short.",
"Issue only proves handling of material. It does not prove position in the critical window.",
"Clinic continuous handling and shortcut-break record",
"Handling signatures, witnessed intervals, and flooded-road repair report.",
"From 22:19 ZhaoChenghai assisted continuously in the clinic to 00:05; several people signed in joining segments.",
"22:16 the shortcut closed for standing water; the detour cannot cover the latch critical window.",
"Latch fiber versus sandbag closing stock",
"Latch residual fiber, flood-cord batch, and sandbag write-off.",
"Latch residual is old cotton, left twist; flood issue is new poly-cotton, right twist.",
"The missing temp reel was written off in next-morning sandbag tying closing stock.",
"Behind-wall paper 1998 seal list",
"Bag number, page count, missing corner, and 2004 page-by-page scan matching fields.",
"Paper was sealed 1998 as bag E98-D-044; page count and lower-right missing corner already registered.",
"2004 scan matches the same bag page by page; digital hash covers scanned body only.",
"1982 Huaixian Daily issue and bound-volume catalog",
"Issue catalog, film frame, and county-library borrow stamp.",
"1982-06-18 p.4 is on that day's issue catalog; the bound volume has the same page, same sentence, and an 1982 borrow stamp.",
"2004 scan and 2012 OCR correction do not change that edition's publication time.",
"BF-11 five-frame contact sheet, keeping perforations, time ruler, water staff, and road-sign refs.",
"NegBag BF-11 digital contact sheet · read perforation order against the photo log",
"AV-04 audio waveform and time ruler; two time-signal points and six unordered event segments are visible.",
"AV-04 waveform view · set time-signal anchors first, then read relative order",
"1998 OldTemple survey plan labeled outer outline, inner wall lines, door, scale, and survey points.",
"1998 OldTemple resurvey · values must close under one coordinate and one scale",
"1964 WheelLamp book and voucher base-text digital image; paper, columns, notes, and damage edges are visible.",
"1964 base-text image · read 户, rotation, handover, and withdraw clauses in original columns",
"1970–1974 Overwrite-text digital image; added strokes, scraping, and ink-color difference sit in the original columns.",
"1970—1974 Overwrite layer · read in layers against the 1964 base text",
"Local comparison crops of base text and Overwrite layer, including key characters, scrape edges, and ink joins.",
"Version-detail crop · the erratum page only marks layers; it does not guess missing characters",
"1982-06-18 Huaixian Daily p.4 whole-page microfilm; masthead, column order, and body blocks are visible.",
"Huaixian Daily 1982-06-18 p.4 · OCR is locator only; glyphs follow the whole-page image",
"1998 continuous footprints and exit route; survey points from behind-wall door, MainHall, to porch joined in time order.",
"F-02 continuous footprint route · route and bridge-head negatives are described separately",
"1964 NorthSlope old-bound bearing drawing with north, bound line, bound marks, temple doors, and refs.",
"1964 NorthSlope old-bound map · check north and scale first, then register to the 1998 route",
"Registration overlay of 1964 old bound line and 1998 exit route; two coordinate refs and the door overlap are visible.",
"1964 old bound—1998 exit-line registration · read only the spatial crossing of route and bound",
"Component relation drawing of inward double doors, pivot wood bar, receiving slot, guide ring, temp pin, and door gap.",
"DOOR-98-A component measure · component fit is recorded apart from operator identity",
"Trace record of door bar, temp pin, guide ring, and door gap; fiber, scratch, bearing, and measure points are visible.",
"Door-part traces · read against the component measure drawing",
"AV-04 waveform versus E1–E6 event cards; cards note sound type only, not speaker.",
"AV-04 accessible event cards · align with the same-track waveform",
"E98-P-017 human-voucher 1964 base-text digital image; original columns, damage edges, and paper marks are visible.",
"E98-P-017 human voucher · base-text image and custody chain described in separate columns",
"1982-06-18 p.4 whole-page image; can be crossed with issue catalog, film frame, and bound-volume stamp.",
"1982 p.4 whole-page image · for issue, carrier, and borrow-time check",
"Latch-trace record page; can be compared with flood-cord batch, twist, and sandbag closing accounts.",
"Latch fiber—flood closing-stock comparison · trace fields and issue ledger are read apart",
"Registration overlay of 1964 old bound line and 1998 exit line.",
"Registration overlay · crossing meaning and tally-holding status are registered apart",
"1998 F-02 footprints and exit-route original drawing.",
"F-02 exit-route original · check route survey points before overlay",
"Same-scale local comparison of 1964 base text and later Overwrite layer.",
"Version-detail comparison · read with the full-page base text",
"Local comparison of Overwrite-layer scraping, added strokes, and cover paper.",
"Overwrite detail · read by paper layer, ink layer, and stroke edges",
"1970–1974 Overwrite text full-page image.",
"Overwrite full page · view in layers with the erratum crop",
"Full-page image of the 1970–1974 Overwrite layer on E98-P-017.",
"E98-P-017 Overwrite layer · described apart from 1964 base text and custody nodes",
"2026 · pending disposition plan card",
"Volume-number return",
"Classify · volume-number layer",
"Two file covers, NegBag tags, 2004 scan-batch catalog, water-damaged emergency OCR remnant page",
"The Migration table put two original files under one spine short and one scan batch.",
"Complete one number mapping from covers and bag tags.",
"Why did the old index write AShan as SoleActor?",
"Two-volume mapping",
"Register cover, scan batch, and NegBag tag column by column.",
"1998 homicide original-file number",
"1998 Landslide original-file number",
"2004 shared scan batch",
"Which 2026 work number should NegBag B's tag see-also",
"HS-98-0717 (homicide file)",
"GR-98-0719 (Landslide file)",
"Look first at the formation year beside each number.",
"Layer as original-file—scan batch—work number. Do not go by literal likeness.",
"The bag tag writes an XGA original file; the catalog currently hangs on a GR work number.",
"Homicide XGA-1998-0717-03, Landslide DZ-1998-0719-11, shared batch HS98-R07; NegBag B returns to HS-98-0717.",
"Claim layers",
"Classify · source layer",
"Old index, forum first/edit/repost, three autopsy abstracts",
"The same old matter left different claims in autopsy abstracts, the Migration index, and the forum.",
"Register the earliest traceable source layer for four claims.",
"Could AShan reach the three violence action zones?",
"Sources of the four claims",
"Check only the earliest traceable material class. Do not judge the teller as a person.",
"'AShan is SoleActor'",
"Original-file field",
"Object mismatch",
"Later work sticky / retelling",
"No matching original-file item",
"'All three self-strangled after fright'",
"One neck injury expanded to three people",
"Later retelling but the object is not wrong",
"Original file has no death record at all",
"'Ice melted and then the door bar dropped'",
"Scene-list confirmation",
"Forum structural guess",
"Autopsy object mismatch",
"Formal exam has proved it impossible",
"'ZhouShouyi blunt head injury'",
"Autopsy original-file field",
"Forum retelling",
"Original file has no such item",
"Put post time and autopsy-formation time side by side.",
"Find the earliest document class each sentence can land on.",
"'Self-strangle' wrongly hung Zhang's neck injury on three people; the ice claim has no scene-list support.",
"SoleActor = later sticky / retelling; three self-strangles = object mismatch; ice melt = forum guess; Zhou head blunt = autopsy original-file field.",
"AShan action zone",
"Overlay · reach",
"Column ring, links, lock pin, lead seal, scale, action zones, tools, and drag layer",
"Column-ring measure card and two trace drawings use the same base, but they are not yet shown merged.",
"Pick layers that take part in the overlay and save one reach opinion.",
"Could the latch really be finished from outside the door?",
"Action-zone overlay",
"Tick layers that actually took part in registration, then pick one opinion that can go on the return.",
"Layers needed for overlay",
"Scale and column-ring base",
"Link max reach",
"Two violence action zones",
"Tool position and no-drag layer",
"Face guess",
"Conclusion that can be saved",
"AShan has no legal responsibility",
"Present material does not support AShan reaching the violence action zones or being the sole actor",
"The other person who left must be the actor",
"Beside the body position there are still 'action zone' and 'drag' switches.",
"Intersect reach with force zones using the scale, and exclude extension tools / drag.",
"Need four layers: scale, max reach, two action zones, tools and drag.",
"Pick scale, reach, force, drag; conclusion only as far as 'present material does not support reaching the action zones or being the sole actor'.",
"Sound order",
"Order · tape calibration",
"AV-04 dual time signals, waveform, transcript, continuous noise floor, and post-drop recording",
"AV-04 has transport drift. The waveform keeps two time-signal points and six event segments still to be ordered.",
"Calibrate the track with the time signals and submit the sound-event order.",
"How to pull the pin from outside and recover the cord?",
"AV-04 relative order",
"Tick calibration points first, then drag-order event cards; keyboard input uses comma-separated codes.",
"Calibration anchors",
"22:30 time signal",
"23:00 time signal",
"Recorder drop",
"23:44 negatives",
"Event order",
"Panel open",
"Barefoot land",
"Impact",
"Lift bar",
"Close door",
"Drop slot",
"The two on-the-hour time signals on the waveform are fixed anchors.",
"Calibrate transport first, then left-to-right on the waveform. Do not use negative time as the tape anchor.",
"Panel open and land are before impact; lift bar, close door, drop slot are after impact.",
"Anchors 22:30, 23:00; order: panel open→barefoot land→impact→lift bar→close door→drop slot.",
"Latch candidate",
"Component model · structural check",
"Inward double doors, pivot wood bar, temp pin, guide ring, fiber, and scratches",
"Component measure, trace record, and a user's ice-prop trial now sit side by side.",
"Pick one checkable latch scheme and tick traces that fit it.",
"Who could be outside the door that night?",
"Ordinary building-component check",
"Register candidate schemes from component geometry and trace fields. This table has no operator column.",
"Scheme that can be finished from outside and recover the cord",
"IceBlock temp-propping a wood bar",
"Single cord pulling the bar directly",
"Taper temp pin + guide ring + knotless U recover-cord",
"Scene items that fit the candidate",
"8 mm temp pin",
"Double old-cotton fiber",
"Axial scratch",
"Drop-slot sound about 4s after close door",
"Meltwater ditch",
"Ask first which scheme lets the whole cord come back from outside.",
"Model 'prop—close door—pull pin—drop slot—pull back U cord'.",
"Check iron pin, double fiber, axial scratch, and delayed drop-slot sound; the scene has no meltwater item.",
"Scheme is temp pin + guide ring + knotless U recover-cord; traces pick pin, fiber, scratch, sound.",
"Eight-person register",
"Dedupe · first-entry rule",
"Temple handover, health-worker sign-in, culture-hall introduction, door register page",
"Four forms separately record present, entered yard, entered hall, and sign-in. Names and document numbers repeat.",
"Unify the count rule, finish person dedupe and exit marks.",
"Can the distant man on the negatives exclude these eight?",
"MainHall first-entry merge",
"Pick the rule first, then merge repeat sign-ins by document number, then read the exit column.",
"Count rule",
"Had been to the temple yard",
"Name appeared on a form",
"Still alive 21:30—23:30 and first full-body crossing into MainHall",
"Eight registered persons",
"ZhaoChenghai",
"LiuQingyu",
"AShan",
"ZhangDafu",
"LiYouye",
"ZhouShouyi",
"SunGuilan",
"LinQing",
"PatrolClerk",
"Three who had left before 22:10",
"Split 'present' from 'full-body crossing into MainHall' first.",
"Dedupe by document number, then class by first full crossing and exit time.",
"The list does not include PatrolClerk, who only reached outside the door 00:04 next day; left before 22:10 are Zhao, Liu, Sun.",
"Rule pick full; eight are Zhao, Liu, AShan, Zhang, Li, Zhou, Sun, LinQing; early leavers Zhao, Liu, Sun.",
"Bridge-head M1",
"Frame match · time and direction",
"BF-11 whole strip, before/after frames, perforations, road sign, water staff, and photo log",
"BF-11 old thumbnail missed before/after frames. The whole strip and same-bag photo log are now added.",
"Align frame order, bearing refs, and contemporaneous whereabouts, and register the minimum description of M1.",
"Can the scene independently define another unknown activity chain?",
"BF-11 whole strip",
"Drag-order five frames by perforation order, then read with the 23:44 whereabouts table.",
"Frames 11—15 order",
"Water-staff empty",
"Flood worker foreground",
"Road sign and distant man",
"Man along the out-of-village direction",
"Empty",
"What can BF-11 prove",
"M1 is LinWen/U1",
"M1 had entered MainHall",
"At 23:44 a man not in the eight-person exit record walked toward out-of-village",
"M1 came from the north-wall space",
"The whole strip has more before/after frames and direction refs than the old thumbnail.",
"Compare only frame order, sign direction, time, and eight-person whereabouts. Do no face ID.",
"Order is water-staff empty→flood worker foreground→sign and distant person→out of village→empty.",
"Order that way; conclusion only unregistered. It does not connect U1, MainHall, or the north-wall space.",
"Building delta",
"Overlay · volume difference",
"OldTemple outer outline, 1998 inner survey, wall thickness, and known rooms",
"The 1998 resurvey gives outer outline, inner wall lines, wall thickness, and numbered rooms together.",
"Do one building close under the same coordinate and scale.",
"When did someone live here?",
"North-wall delta calculation",
"Unify coordinate and scale first, then subtract wall thickness and numbered rooms from the outer outline.",
"First step",
"Unify outer outline and inner survey to the same coordinate/scale",
"Looks close enough from a screenshot",
"Assume first that the abandoned mine connects",
"Delta after subtracting wall thickness and known rooms",
"1.18 × 6.8 m",
"1.8 × 8.6 m",
"184 m, 26 m lower",
"What can this delta show for now",
"There is an unnumbered behind-wall space",
"Confirm this was used to confine LinWen",
"Confirm a mine-adit entrance",
"Handle coordinates and scale of the two drawings first.",
"After unifying coordinates, subtract wall thickness and all known rooms from inside the outer outline.",
"Result is 1.18×6.8 m; the drawing only supports an unnumbered space.",
"Pick same, 1.18x6.8, room. Do not infer occupant or use from the delta.",
"Years of living",
"Classify · time bounds",
"Medicine bag, repair thread, soot, food port, pack lot, and fresh break",
"The behind-wall object card records pack lot, repair layer, seal number, and break state together.",
"Use time bounds and horizon relations to order four object cards.",
"Is the behind-wall occupant U1?",
"Living-layer time constraint",
"Mark known years and time bounds first, then order by horizon relation.",
"Order from early to late",
"1974 repair-thread lower layer",
"Medicine bag not before 1982",
"Paper sealed before 1998",
"1998 rescue fresh break",
"Scope that can be saved",
"The same person was behind the wall every day 1975—1998",
"This space has living traces across several years; specific continuity is checked separately",
"These objects already confirm the occupant is U1",
"A pack lot supplies bounds, not necessarily a use day.",
"Split 'known year' from 'earliest/latest not-before', then order by relative stratigraphy.",
"1974 repair thread below, then 1982 medicine bag, then paper sealed before 1998, then 1998 fresh break.",
"Order repair74→medicine82→paper98→break98; scope only layers.",
"U1, Ninth, and conduct bounds",
"Compare + classify · four panels",
"P-07/D-03/W-02/F-02, eight-person table, kin/trait screen, U1 identity-conjunction return, five conduct propositions",
"U1's anonymous sample, entry record, identity fields, and conduct propositions sit in four table sets.",
"Check panel by panel in order. Save each one separately.",
"Why was he behind the wall, and what does 'one person' in the old material mean?",
"Confirmed",
"U1 = LinWen.",
"Still unresolved",
"Whether bridge-head M1 is U1 / LinWen.",
"Material cannot carry it",
"LinWen caused three adult deaths.",
"Panel 1/4: anonymous sample merge",
"Name column is closed for now. Check only sample keys, footprint continuity, and custody chain.",
"Merge keys",
"Sample profiles match",
"Left-second-toe trait and continuous footprints",
"Each piece's custody chain is auditable",
"BF-11 distant face",
"This panel does not prove",
"Name, motive, and lethal responsibility",
"These samples can be grouped as the same U1",
"Cover all names first.",
"Do anonymous merge with sample profile, footprint continuity, and custody chain only.",
"BF-11 does not enter U1 sample conjunction.",
"Pick profile, toe, custody; this panel does not prove identity.",
"Panel 2/4: first full-crossing backfill",
"Keep the anonymous U1 from the last sheet and backfill the entry record under the B06 rule.",
"Rule still in use",
"First time the body fully crossed into MainHall",
"Must already have a registered name",
"Caught on negatives",
"U1 at 22:47±1 should be recorded as",
"Ninth living person",
"One of the eight entering again",
"Real-name backfill of bridge-head M1",
"Return to the count rule already set in B06.",
"Put the anonymous U1's actual crossing into the table. You do not need the name first.",
"22:47±1 is first full crossing; the registered eight have no such record.",
"Pick full and nine. This panel still does not connect U1 to M1.",
"Panel 3/4: LinWen identity conjunction",
"This panel only handles U1 real name. The bridge-head person stays anonymous M1 and is not merged into identity conjunction.",
"Identity-conjunction fields",
"U1–LinQing full-sibling relation is strongly supported",
"LinQing has only one recorded full-sibling elder brother, LinWen",
"LinWen 1975 missing window",
"LinWen left-second-toe old injury",
"BF-11 distant face",
"Merge-check on four fields",
"U1 can be confirmed as LinWen",
"M1 can be confirmed as LinWen",
"LinWen can be confirmed as causing three adult deaths",
"Identity screen must have four mutually independent keys.",
"Conjoin kin, family uniqueness, missing window, and old foot injury.",
"BF-11 is not an identity exam; identity confirmation also does not assign a death act.",
"Pick sibling, onlyBrother, missing, toe; identity pick linwen.",
"Panel 4/4: five conduct evidence bounds",
"Identity column is sealed. This table checks contact, exit, and conduct propositions against their own direct sources, one by one.",
"U1 contacted the behind-wall board",
"Can confirm",
"Ruled out",
"U1 contacted the temp pin",
"U1 exited at 23:26",
"U1 finished the outside bar drop",
"U1 caused adult death",
"The same person contacting objects is not the same person finishing every consequence.",
"Each proposition uses only its own direct source. The identity return is not bound to a special latch-operator check.",
"Behind-wall board, temp-pin contact, and 23:26 exit can be confirmed; outside bar drop and adult-death responsibility are not enough.",
"Later-text surface",
"Compare · visible fields",
"1974 human-voucher Overwrite layer, 1982 remnant line, and three anonymous position numbers",
"The 1970—1974 entry and the 1982 paper keep nearby wording, but the two materials sit at different layers.",
"Copy the later text's visible fields and register its source status.",
"Do the three positions correspond to three missing children?",
"Later-text field extract",
"Copy fields from the photocopy page. Do not fill names or efficacy findings into blank columns.",
"Currently visible fields",
"Three anonymous position numbers",
"One person fixed on watch",
"No next hand arrives, previous watch does not withdraw",
"Three children's names",
"Non-human already-received finding",
"Source judgment",
"Recorded as 1970—1974 Overwrite layer; do not yet judge reception or rightness",
"Already proved this is original ancient custom",
"Humans altered it so it must be void",
"Copy the fields first. Do not explain them.",
"Split 'what the text writes' from 'whether it is original / valid'.",
"Visible are positions, fixed watch, and no next hand; children's names and reception are not on the page.",
"Pick positions, fixed, noNext; status pick record.",
"Three renamed",
"Independent checks · three short jobs",
"Three different life materials, last records, official whereabouts, reception gaps, individual traits, and kin",
"Three historical whereabouts all have breaks. The project requires three identity sheets registered separately.",
"Finish FangXiaohe, DengMei, and XuYousheng independent check sheets in order.",
"Do the three correspond to three anonymous position numbers?",
"FangXiaohe | inbound copy never returned",
"Fill her sheet from school, transfer copy, old injury, and kin material. Do not borrow the other two's traits.",
"Which four join into FangXiaohe's identity chain",
"1971 last-at-school record",
"'Moved with kin' but receiving place has no inbound receipt",
"Living full-brother model",
"Maxillary deciduous-molar treatment mark",
"How far can this return be written",
"Identity chain can stand; cause of death and actor still unresolved",
"Empty inbound record proves she was killed",
"Find 1971 school, move-out reception, left-forearm old injury, and brother kin.",
"Life record→whereabouts gap→individual trait→independent kin.",
"The deciduous-molar trait belongs to someone else and cannot be borrowed.",
"Pick school, move, radius, brother; bound pick identity.",
"DengMei | 'died of illness' that never landed in a reception book",
"Check health card, three reception books, dental trait, and mother-daughter material; do not fill a cause of death into blanks for her.",
"Which four materials belong in DengMei's column",
"School health card and last record",
"'Died of illness' but hospital/village doctor/cemetery have no reception",
"Living mother-daughter model",
"How to write after the reception books are blank",
"Identity chain can stand; empty records do not prove drug, cause of death, or an actor",
"Empty cemetery record proves a specific cause of death",
"Find 1973 health card, medical/cemetery reception, dental trait, and mother kin.",
"Empty records only exclude the official reception chain. They do not auto-fill a death mechanism.",
"The right-tibia trait belongs to XuYousheng.",
"Pick card, hospital, dental, mother; bound pick identity.",
"XuYousheng | after the search notice",
"Keep vaccine card, river reception, tibia trait, and sister kin on this one sheet. One errand record is not a final whereabouts.",
"Besides the search notice, which fields belong to XuYousheng",
"1974 vaccine card/last record",
"'Drowned missing' but the river has no unnamed-child reception",
"Living full-sister model",
"Left-radius healed deformity",
"How far can this river clue narrow",
"Identity chain can stand; river empty record does not prove the course of death",
"Engineering at the same time proves ritual motive",
"Find 1974 vaccine/last record, river reception, right tibia, and sister kin.",
"Conjoin independent life record, whereabouts exclusion, individual trait, and kin.",
"Left radius belongs to FangXiaohe; construction at the same time also does not prove motive.",
"Pick vaccine, river, tibia, sister; bound pick identity.",
"Name and position",
"Match · anonymous first, then rename",
"HR-01/02/03 anonymous units, three floor works, three position numbers, and confirmed identity results",
"HR-01, 02, 03 are described first as excavation units. Name-correction records sit on another layer.",
"Finish anonymous-unit matching first, then attach checked names to the modern catalog.",
"If the match stands, was this really original ancient custom?",
"Screen 1/2: anonymous unit—position match",
"Name field is not open yet. Match only by unit number, engineering layer, and position number.",
"UNIT-G14 / HR-01 (1971 floor layer)",
"POS-EAST-1 / east post 1 / 1971",
"POS-WEST-2 / west post 2 / 1973",
"POS-NORTH-3 / north post 3 / 1974",
"UNIT-G16 / HR-02 (1973 relay layer)",
"UNIT-H15 / HR-03 (1974 cover layer)",
"This match cannot prove",
"Cause of death, actor, or ritual motive",
"Space and year correspondence",
"Look only at anonymous numbers, work period, and position year first.",
"Let the three year-groups match the three construction layers one-to-one; names attach on the next screen.",
"1971→east post 1, 1973→west post 2, 1974→north post 3.",
"Screen 2/2: modern-catalog rename",
"Pull the three independent identity returns and update only the modern catalog's name field.",
"Modern-catalog name for UNIT-G14 / POS-EAST-1",
"Modern-catalog name for UNIT-G16 / POS-WEST-2",
"Modern-catalog name for UNIT-H15 / POS-NORTH-3",
"Bound after rename",
"Only identity-to-space correspondence is formed; death responsibility, cause of death, and ritual motive still unresolved",
"Name match confirms ritual killing",
"Use B12's three independent identity returns.",
"Names attach only on the modern-catalog correction view. They are not written back onto the old compact.",
"East post 1 corresponds to FangXiaohe, west post 2 to DengMei, north post 3 to XuYousheng.",
"eastName=FangXiaohe, westName=DengMei, northName=XuYousheng; nameLimit=identity-only.",
"Original-compact restore",
"Version compare · ink-layer order",
"1964 human voucher, WheelLamp book, lamp-oil issue, ditch-patrol pages, and 1970—1974 Overwrite layer",
"1964 base text and 1970—1974 Overwrite layer can be aligned place by place by columns, ink color, and scrape edges.",
"Rebuild base-text fields and mark how the Overwrite layer changed relations.",
"Do the rewritten object relations still stand?",
"1964 base text and 1970—1974 Overwrite",
"Left column copies the base text; right column copies the Overwrite layer; efficacy opinion is not on this version table.",
"1964 original system",
"Three households, each a lamp, shared duty",
"Each round one household sends an adult NightWatch person",
"Inside ThreeNights the next hand takes over, previous hand withdraws",
"There is a clear compact-withdraw method",
"Three children fixed at lamp posts",
"1970—1974 rewrite",
"Household→position",
"Rotation→fixed watch",
"Withdraw clause covered",
"Original writes three children's names",
"How far can this be written for now",
"Human scrape Overwrite can be confirmed; whether it was received is still unresolved",
"The form is complete so it must be valid",
"Split the 1964 ink layer from the later ink layer.",
"Compare whether household/position, adult rotation/fixed watch, and the withdraw clause are still visible.",
"Original system has three households, adult NightWatch, ThreeNights tally handover, and withdraw; later writing changes three relations.",
"original pick households, adult, handover, withdraw; changes pick h2p, rotate2fixed, cover; effect pick human.",
"Guard-tally source",
"Check · object source chain",
"Guard tally, handover tail voucher, behind-wall living layer, bags, and transfer records",
"E98-O-031 guard tally and the handover tail voucher sit on two cards, but both kept number, notch, and cord records.",
"Check object traits and custody nodes and save one correspondence opinion.",
"When U1 left, was it the ordinary main door or the old watch bound?",
"Guard tally—tail-voucher correspondence",
"This table only takes object traits and store nodes. Do not fill blanks from a person's self-report.",
"Object correspondence fields",
"Tally numbers match",
"Old notches correspond",
"Cord wear matches the rubbing",
"1998 in-place photo through 2026 in/out continuous",
"U1 self-report of willingness to watch the mountain",
"Conclusion bound",
"Confirm the object number group and source chain; do not confirm U1 took folk watch",
"Confirm U1 is a willing watcher",
"Split object fields from person-role fields.",
"Check tally number, notch, wear/rubbing, and custody chain.",
"No contemporaneous source records that U1 understood, agreed to, or took the duty.",
"Pick number, notch, wear, custody; scope pick object.",
]
print("EN2", len(EN2))
