# English lines 1000-1444 matching quoted_copy.json
EN3 = [
"Old-bound threshold",
"Registration · route crossing",
"1964 bearing map, 1998 plan, rescue record, and 23:26 exit route",
"The 1964 old-bound map and the 1998 exit map share three survey points, but north and sheet scale are not yet aligned.",
"Register the two maps and log where the exit route crosses the old bound line.",
"Which night does ThreeNights start from?",
"1964 old bound—1998 route registration",
"Tick layers that take part in registration, then read the crossing from the overlay.",
"Needed for registration",
"North and scale of both maps",
"1964 old watch-bound threshold line",
"1998 23:26 actual exit route",
"23:44 negative face",
"Crossing",
"At 23:26 the main door crossed the old-bound threshold",
"At 22:47 from the behind-wall space into MainHall",
"23:44 bridge head",
"Still cannot confirm",
"U1 actually took folk watch",
"U1 crossed the old threshold",
"Find the threshold line on the old bearing map first, not the behind-wall small door.",
"Register north, scale, and the main door, then overlay the 23:26 exit route.",
"The crossing is the 23:26 MainHall outer door; the negatives do not take part.",
"Pick orientation, threshold, exit; cross=2326; limit=role.",
"Third-night calculation versus first report",
"Calculate · full night shift",
"1982 remnant line, 1964 ordinary rotation instance, 23:26 exit, and 1998 geology first report",
"The work order requires the folk-clause shift rule and the geology report time to be handled separately.",
"Submit one condition-calculation sheet first, then compare the sealed window with the first report.",
"Is 2026 professional disposition only a neutral test?",
"Calculate first: the third full night",
"This page only records conditions, the start point, and three full night shifts. Timezone is Asia/Shanghai. The first report waits for the next page.",
"Calculation premises",
"If the 23:26 bound-leaver then actually held the tally, and no living next hand kept taking over inside the bound",
"The file has already confirmed U1 actually held the tally and took folk watch",
"No premise needed; use exit time only",
"T0 when the condition holds",
"First night",
"Second night",
"Third night",
"Exactly 72 hours after T0",
"Write the ‘if actually held the tally and no next hand’ condition first; the start evening is not a full night shift.",
"Count nights from the first full 18:00—06:00 night shift after the condition start.",
"Night 1 starts 07-17 18:00; night 3 is 07-19 18:00 to 07-20 06:00; timezone Asia/Shanghai.",
"Premise pick ‘if actually held the tally and no next hand’; start 07-16 23:26; nights 07-17, 07-18, 07-19. Save, then open the first-report comparison.",
"Then look: does the first report fall in the window",
"The previous page's window is sealed. Open the first report, copy its time and place, then compare intervals.",
"Compare with the first report",
"If the premise holds, the 1998-07-19 23:41 first report falls in the third night and the place is NorthSlope",
"Time coincidence proves supernatural cause of the landslide",
"The first report is not in the third night",
"Copy the first report's date, time, and place first. Do not explain cause.",
"Put 23:41 back into the previous screen's third-night 18:00—next-day 06:00 window.",
"The first report is 07-19 23:41 at NorthSlope; it falls inside the third night.",
"Pick ‘if the premise holds, the first report falls in the window’. This only forms a conditional coincidence. It does not confirm actual tally-holding or supernatural cause.",
"Object sources and informed disposition",
"Source check + preview + advice",
"Human voucher / mountain-notice counterpart / guard tally — three independent source cards and A/B live-action previews",
"The three originals sit on different custody chains. The two candidate plans differ on move, contact, and rollback.",
"Clear the three sources, read both disposition cards, then submit one piece of advice.",
"The project only records live execution; extra causation stays unresolved on present material.",
"Screen 1/3: each original's own source",
"Register by find place, seal number, and current custody body. WT-26-04 is not a physical-merge credential.",
"Human voucher + tail voucher",
"Taken 1998 from the MainHall east cabinet, police restricted custody; 2004 scan only",
"2026 found in situ in the NorthSlope voucher niche",
"Taken 1998 from the behind-wall living layer",
"Mountain-notice counterpart",
"Taken 1998 from the MainHall east cabinet",
"2026 found in situ in the NorthSlope voucher niche and sealed into store continuously",
"Sealed with the human voucher at opening",
"Guard tally",
"Photographed in situ in the 1998 behind-wall living layer, then bagged separately",
"2026 niche find",
"2004 sealed with the two vouchers",
"Physical effect of digital checking",
"Reading, OCR, alignment, and saved advice did not change original-object state",
"Database linking has already put the originals together",
"Look first at each card's ‘find/taken place’ and ‘current custody body’.",
"Keep the 1998 east cabinet, 1998 behind-wall, and 2026 niche chains apart.",
"Human voucher at the east cabinet; guard tally behind the wall; mountain-notice counterpart at the 2026 niche.",
"Screen 2/3: six live-action preview",
"Both cards are pending disposition plans. Register by number, action, removal, rollback, and conclusion bound, row by row.",
"Confirm you have looked item by item",
"Independent numbers, current custody body, and state",
"A's RQ-01 and B's minimum-intervention aim",
"Authorized staff, time, place, and physical actions",
"Removal, reception, return, and final accession body",
"Cancel conditions and exception rollback",
"What this round can actually move, and what the material still cannot say",
"Your authority",
"I only submit disposition advice; approval, reception, and execution are done by the corresponding agency handlers",
"I approve and receive the originals",
"Each plan card has six rows. Do not stop at the title.",
"Compare live purpose, physical action, cost, rollback, and conclusion bound.",
"The form-filler's authority stays at submitting advice.",
"Tick ids, questions, actions, returns, cancel, limits; authority pick recommend.",
"Screen 3/3: submit disposition advice",
"After save, a disposition-advice receipt is formed. You do not receive original-object approval, reception, or handling power.",
"Disposition advice",
"A: controlled, time-limited, piece-separate same-room original-object exam",
"B: piece-separate protection and bounded digital see-also",
"Submit confirmation",
"This is advice, not approval",
"Does not rewrite historical original files",
"Child-death responsibility and extra supernatural causation stay unresolved",
"What you pick is live disposition advice, not a folk stance.",
"A adds one controlled original-object operation to answer a narrow question; B accepts the present bounded opinion with minimum movement.",
"Both plans finish professionally. Neither resolves child-death responsibility, whether the compact was withdrawn, or extra causation.",
"Pick A or B as the informed advice you would file, and tick advice, original, unresolved. This hint does not recommend a branch.",
"Chapter 1  The old index outran the original file",
"Chapter 2  The ninth did not come from outside",
"Chapter 3  So-called ancient custom was later rewritten",
"Chapter 4  Calculate the third night first, then decide whether to restage the relation",
"Still on scene, so AShan may be SoleActor",
"Still on scene is not the same as reaching the violence action zones; the old-index SoleActor link is ruled out",
"The man on the negatives may be one of the eight registered persons",
"Only one unregistered man is confirmed; it does not prove he entered MainHall, equals U1, or came from the behind-wall space",
"The old drawing is complete; there is no long-use space behind the north wall",
"The drawing is incomplete; an unnumbered behind-wall space exists",
"The behind-wall occupant, the pin-contact person, and the exit footprints may be different people",
"Sample keys and footprint continuity support the same U1",
"U1 lived behind the wall but may not have fully crossed into MainHall",
"By the set count rule U1 is the Ninth living person",
"U1 may still match more than one historically missing male",
"Multi-key identity conjunction confirms U1 as Lin Wen",
"Three posts and one watch is original ancient custom",
"1964 is adult mutual NightWatch rotation; later someone damaged household, rotation, and withdraw clauses",
"Rename and exposing the rewrite already equals compact withdrawal",
"Digital correction did not change the physical relation of guard tally, tail voucher, old bound, and exit",
"The third night is a later back-calculation from the disaster date",
"If the 23:26 bound-leaver actually held the tally and no one took over, the pre-case third-night window coincides with the first report; the premise and extra causation stay unresolved",
"Professional exam is necessarily folk-neutral",
"A live lawful action may restage a material relation the old text admits; present material cannot confirm its folk consequence",
"Archive-catalog maintainer",
"IDX-XGA98-ASHAN-2004 is now hung as an ‘old-index dispute item’. The old title is kept so the Migration mis-hang can be checked; the box-side sticky still has no named author. Volume mapping is logged on WT-26-04.",
"Audio and door-body measure cards are now on this sheet's see-also.",
"Film digitizing room",
"The old BF-11 thumbnail was cut from a middle frame; the negatives themselves were not short. Frames 11—15 and the photo log are now restored by perforation. Distant resolution is not enough for face ID.",
"You can open it from the Negatives catalog ‘whole strip’ entry.",
"Old-building surveyor",
"I turned the old survey draft. That north-wall stretch was drawn as solid wall even before the 1998 rain repair. It never had a room number. I can sign the drawing history. Who lived inside is not on the survey draft.",
"Repair ledgers and the old-compact catalog are now on the see-also.",
"Family liaison",
"Fang Xiaohe, Deng Mei, and Xu Yousheng name corrections are registered separately. A set name is no longer used. Liaison notes use only each family's authorized fields.",
"The folk-site version erratum is a separate record.",
"Liaison notes",
"Huaibei folk-materials site desk",
"Version record",
"The 1974 entry is now hung as ‘later text, source layer pending’. Original URL, old page, and past citations are kept; each page head points to the erratum.",
"NorthSlope geology team",
"BP-1998-0719 cumulative rain, shale softening, seepage, and toe scour already suffice for a local landslide. The shift table you filed is a condition calculation: if the bound-leaver then actually held the tally and there was no next hand, the first report falls in the sealed window. Those two premises are not geology-report columns.",
"The return keeps condition comparison and natural mechanism in two columns. Premises stay unresolved.",
"Project QC office",
"QA-26-0813-447 disposition advice is logged. Current business state: material QC closed. Original-object authorization, reception, and physical handling are outside QC-447 authority.",
"The work order is sealed. Later handling follows the agency-approval receipt.",
"Zhao Chenghai and the red cord",
"Latch fiber + flood-material assistant field on the eight-person table",
"The person who signed two reels and was short one next day may have worked the latch from outside",
"The critical window cannot cover a round trip; new poly-cotton does not match old left-twist cotton; the missing reel went to sandbags and closed normally.",
"Time, material, and accounts must all agree",
"Only Zhao Chenghai working that latch is excluded. It does not prove U1 killed or that Lin Qing took part.",
"Time, material, and account fields together first take down which claim?",
"Zhao Chenghai operated that latch candidate",
"U1 caused three adult deaths",
"Lin Qing took part in the outside bar drop",
"Issue and temp stock",
"Excerpt material, issue count, and temp-stock state.",
"Clinic and shortcut break",
"Excerpt continuous presence in the critical window and road state.",
"Latch and flood fiber",
"Excerpt the latch fiber's own batch/twist fields.",
"Fiber and closing stock",
"Compare the two fibers and check where the missing reel finally went.",
"2004 diary forgery",
"Creation time of the PDF attached to the behind-wall pack card",
"A PDF created in 2004 may have been forged to fit old-case talk",
"The paper was already sealed in 1998; 2004 is page-by-page digitizing only.",
"File-generation time is not original-formation time",
"Only confirms the paper predates digitizing; the diary's folk-rule claims are not auto-proved.",
"These formation and seal times first take down which claim?",
"The paper text was forged in 2004 to fit old-case talk",
"The diary's folk-rule claims must be true",
"The paper author's identity is confirmed",
"Scan-batch properties",
"Split digital-file creation time from paper formation time.",
"OCR correction layer",
"Excerpt whether image, scan, and OCR fields each change.",
"1998 seal list",
"Check bag number, page count, and when the missing corner formed.",
"Page-by-page scan scope",
"Excerpt what the hash scope can and cannot prove.",
"Abandoned-mine adit",
"‘Old mine behind the temple’ in a folk travel note + the unregistered bridge-head person",
"The unregistered person may have entered MainHall through the old mine",
"The end is 184 m from MainHall and 26 m lower, continuous shale in between, no through-cut.",
"Plan distance must be compared with elevation and section at the same time",
"The old mine is excluded. The north-wall building interlayer is not excluded early.",
"Coordinate, elevation, and section together exclude which connection?",
"The old mine can be U1's route into MainHall",
"A building delta exists at the north wall",
"A natural landslide will occur on NorthSlope",
"Old-mine-behind-temple travel note",
"Excerpt oral direction and the missing spatial fields.",
"1992 closure plan",
"Excerpt entry, end, and seal-off records.",
"Coordinate and elevation method",
"Excerpt why plan-nearness cannot replace elevation and section.",
"Seal-off and section recheck",
"Check distance, elevation difference, and continuous rock.",
"Same-name Lin Wen",
"Old-paper search ‘Lin Wen’",
"A 1996 farm-machine-plant prizewinner would mean the missing Lin Wen still lived in public",
"This is another adult, born 1964, west-city address, continuously on post.",
"A name cannot replace birth year, address, and continuous work history",
"It does not give U1 proof or disproof.",
"Birth year, address, and continuous history exclude which connection?",
"The 1996 prizewinner is the 1975 missing Lin Wen",
"The U1 identity chain stands",
"Bridge-head M1 is Lin Wen",
"Prize news",
"Excerpt the identity fields the report actually gives.",
"Staff register",
"Excerpt birth year and address.",
"Continuous history",
"Excerpt continuous on-post years.",
"News recheck",
"Confirm the news has only name and unit; it cannot cover register fields.",
"The 1982 paper is a later reprint",
"The scan file was made 2004; OCR was corrected 2012",
"The ‘third night’ remnant line may have been written after the 1998 case",
"Microfilm, issue catalog, and an 1982 borrow stamp show that sentence was already public then.",
"Body time, carrier-copy time, and OCR-correction time must be split",
"Only confirms a pre-case text. It does not prove that text caused a landslide.",
"Publication, scan, OCR, and borrow times exclude which claim?",
"The 1982 remnant line was written only after the 1998 case",
"The remnant line caused the 1998 landslide",
"The remnant line proves the folk rule is effective",
"Whole-page image",
"Excerpt publication date, edition, and film frame.",
"OCR correction",
"Split the 2004 scan from the 2012 retrieval-text correction.",
"Issue and bound volume",
"Check the issue catalog and the 1982 borrow stamp.",
"Before/after-edition recheck",
"Check film before/after editions and 118-frame continuity.",
"Controlled, time-limited, piece-separate same-room original-object exam",
"Pending candidate · archive/heritage accuracy not outside-reviewed",
"Answer the narrow question RQ-01 while each piece keeps its own support and they do not touch or join.",
"The three originals enter the same exam batch under independent paperwork, packing, and seals; the original file only supplies certified data.",
"Each original enters its own cell in one outer calibrated fixture. They do not touch and do not merge title.",
"Named examiners only compare break-edge micro-deformation and half-seal relative position. No character fill, paper fill, or reprint.",
"Each original agency's handler separately checks seals, opens, watches, reseals, returns, and accessions.",
"Cancel if any approval, site, state, seal, or transport condition is not met.",
"After execution, live action and a bounded opinion can be confirmed. The 1974 operation, folk efficacy, and extra causation cannot.",
"On the third full night a low-amplitude local displacement occurred; no one was hurt. Contemporaneous natural conditions suffice; extra supernatural causation stays unresolved.",
"Piece-separate protection and bounded digital see-also",
"Complete professional plan · not ranked",
"Accept present image / non-destructive bounded conclusions; finish protection and see-also with minimum movement and minimum intervention.",
"The three originals stay independently with their own custody bodies. They do not enter a shared physical fixture.",
"Keep certified high-resolution images, non-destructive tests, and uniformly calibrated cross-agency derived data.",
"Authorized conservation staff choose breathable support, buffering, or suitable packing from present condition.",
"Finds are seal-checked, accepted, and finally accessioned by the named store.",
"Abnormal state rolls back on each piece's own custody procedure. Do not add original-object risk to shrink the unresolved.",
"RQ-01 stays unresolved. This does not confirm the old compact is void, that the children were released, or that extra causation does not exist.",
"Piece-separate protection, bounded digital see-also, final accession, and routine monitoring are complete. This branch adds no third-night event.",
"Authorized handlers finished independent-cell exam, piece-by-piece return, and accession under the disposition procedure.",
"The third full night recorded a low-amplitude local displacement; no one was hurt. Natural explanation is sufficient.",
"Authorized handlers finished piece-separate protection, digital see-also, final accession, and routine monitoring.",
"There is no third-night event exclusive to this branch. That cannot confirm the old compact is void or that the children were already released.",
"Gazetteer photo-direction label recheck",
"Filed",
"Water-damaged volume page-continuity spot check",
"Waiting on admin confirm",
"Same-name creator-field merge returned",
"Returned",
"Film-bag number versus process-number check",
"OCR date-misread recheck",
"In process",
"Cross-fonds see-also spot check",
"Pending QC",
"Old-map coordinate-system note fill",
"Open-catalog privacy-field patrol",
"Whether M1 is U1 / Lin Wen",
"Provable assignment of the three adult-death actors",
"All 1970—1974 rewriters and their exact split of work",
"Each of the three children's cause of death, actor, and ritual motive",
"Whether U1 actually took folk watch",
"Whether the 1974 later relation was received by a non-human",
"Whether the 1998 and Plan-A landslides include extra supernatural action",
"Whether the old compact was already withdrawn at this-round material cutoff",
"Huaishu",
"Ninth",
"IceBlock",
"SourceCode",
"AdminPassword",
"SoleActor",
"NegBag",
"Migration",
"MainHall",
"WheelLamp",
"NightWatch",
"Overwrite",
"Negatives",
"Landslide",
"NorthSlope",
"OldTemple",
"Huaixian historical special-file digital QC project — records QC QC-447",
"Content includes historical death, disappearance, long control, harm records involving minors, and remains-identity check. No remains photos, pictured violence, jump-scares, or auto-played sound. You may leave at any time; the current browse session is kept.",
"Death of a minor",
"Long restriction of personal liberty",
"Disability stigma",
"Possible ritualized harm",
"Archive tampering",
"Unconfirmed death responsibility and family privacy",
"Fictional work, test edition. Live professional accuracy of archive and heritage procedure has not had outside review; this is not a professional-compliance opinion.",
"The save event was cut at the first illegal node.",
"That QC panel does not exist.",
"The submit format cannot be read. Please choose again.",
"The submit includes a field this panel does not have. Clear it and retry.",
"One item is still empty:",
"Current field",
"Fields are still empty. Finish the visible check items on this panel first.",
"This combination still has fields that do not agree. Return to the visible material and check item by item with this panel's method.",
"Check items agree.",
"That hint does not exist.",
"Level 4 will show the full executable answer. Please confirm again.",
"The previous project receipt is not yet fully read.",
"There is no project receipt waiting to publish.",
"A new in-project receipt has been published.",
"That QC step does not exist.",
"Start a local QC session first.",
"Return to the workbench and finish the new project receipt first. Public pages stay browsable.",
"Return to the workbench and take the new project receipt first. Public pages stay browsable.",
"The previous derived product is not yet saved. Public material stays browsable.",
"That panel is already saved.",
"Save the current panel first. You may return to view earlier panels.",
"Another piece of advice has already entered the agency-receipt queue.",
"Disposition advice is recorded. Waiting on a fixed agency-authorization event.",
"This item's check return is saved.",
"This panel is saved. You may enter the next panel.",
"B18 source check and advice gates are not yet fully saved.",
"There is not yet advice available for agency handling.",
"Plan A fixture is not declared. It cannot be authorized.",
"The fixed agency has formed an independent authorization receipt.",
"The agency-authorization event is not yet formed.",
"The other branch has already executed. This branch is permanently refused.",
"Fixed staff finished execution. The endpoint receipt is cast.",
"There is no such public-record chain.",
"Start a QC session first.",
"This record has no direct pointer from the current page to the chosen page.",
"Source pages are still not excerpted.",
"This conclusion exceeds what the sources can exclude. First close only the one that fits.",
"Limited exclusion is saved. Main-line gates did not change.",
"Enter one search word.",
"Search one word at a time.",
"Use a single word already on an opened page. Spaces and symbols will not hit a record.",
"There is no such site.",
"This file is forbidden.",
"Sorry, no results related to “",
"”. Try another word from a page you already read.",
"",
" matching result(s).",
"Mountain-Garrison Compact: Ninth Visitor",
"Old post, unsigned",
"Old-matter chat",
"Reply time not kept",
"Mirror has an edit log",
"Reposter unnamed",
"Repost board",
"Last-post time not kept",
"No edit log seen",
"Original ID not kept",
"Carpentry talk",
"Last-post time lost",
"Edit status unmarked",
"Neighborhood number lost",
"Help-post time not kept",
"No edit mark seen",
"Ask-way post unnamed",
"Last-floor time not kept",
"Edit log not kept",
"Life-board unnamed",
"Reply clock not kept",
"No edit seen",
"Alumni ID not left",
"Meetup-post time lost",
"Edit log missing",
"Angler name not left",
"Last-post clock not kept",
"Unnamed",
"Not counted",
"Unclassified",
"Time not kept",
"No edit log seen",
"Table catalog",
"Plan / bearing",
"Timeline events",
"Waveform media",
"Physical traces",
"Plan workflow",
"Five-frame contact sheet, keeping perforations, time ruler, and bearing marks; specific direction must be read with the photo log.",
"NegBag BF-11 digital contact sheet; image, perforation continuity, and photo log are checked in layers.",
"1982 old-paper p.4 whole-page microfilm; masthead, column order, and story blocks are visible.",
"Holdings whole-page image; OCR is locator only. Edition and body follow the image.",
"1998 OldTemple survey plan labeled MainHall, walls, door, scale, and survey points.",
"Public survey drawing; position relations must be read with scale, coordinates, and survey extent.",
"1964 WheelLamp copy-page digital image; paper, columns, notes, and damage edges are visible.",
"1964 copy digital image; transcript and version notes are listed separately. Modern typesetting does not replace the base text.",
"Post-1974 later-text page digital image; different hands, scraping, and Overwrite zones are visible.",
"Post-1974 later-text digital image; version relation and literal efficacy are recorded apart.",
"AV-04 track waveform and segmented time ruler, with several sound start/stop positions, no auto speaker ID.",
"AV-04 waveform view; the waveform only supports relative order and time-segment check.",
"1964 old-bound map digital copy, labeled north, bound line, threshold, and refs.",
"1964 old-bound map; year, north, and threshold position must be checked apart from other sources.",
"1998 23:26 leave-record path map, labeled MainHall, south door, and old-bound threshold.",
"23:26 leave-record path map; a route record does not prove what the person carried.",
"Component-relation drawing of door body, bar, pin, and cord, marking inside/outside and contact points.",
"Door-body component-relation drawing; component fit is not operator identity.",
"Door-bar and pin trace record page, with fiber, scratch, bearing, and measure marks.",
"Door-part trace record page; observation fields and responsibility judgment are kept apart.",
"View the fixed public version record",
"View the whole strip",
"View public survey data",
"View the fixed public erratum",
"View public geology records",
"View the project execution receipt",
"Confirm the attachment hang has a Migration clash; WT-26-04 is only a cross-agency digital-record list.",
"Old index and forum spread cannot replace original-file source layers.",
"The old-index ‘SoleActor’ link is ruled out. That is not a legal no-responsibility finding.",
"Calibration only builds relative sound order. It does not by itself confirm a speaker.",
"The component candidate fits in geometry and traces. Operator and death responsibility still need independent sources.",
"By the first full-crossing-into-MainHall rule, the register can be deduped to eight persons.",
"M1 is only an unregistered man walking out of the village at 23:44. He cannot be joined to U1, MainHall, or the behind-wall space.",
"An unnumbered behind-wall space exists. The delta does not name a user or a use.",
"The space has living layers across years. It cannot fill every day or name someone early.",
"U1 identity, entry count, object contact, and conduct responsibility are layered. Outside bar drop and adult-death responsibility stay unresolved.",
"Only the later-text surface is saved. It is not confirmed as original ancient custom or as already received.",
"The three children are renamed separately. The three identity chains do not share life, trait, or kin sources.",
"Match anonymous units first, then rename on a separate modern-catalog screen. Cause of death, actor, and ritual motive stay unresolved.",
"Human scrape Overwrite can be confirmed. ‘Humans rewrote it’ is not ‘so it is void’.",
"Guard tally and tail voucher belong to the same number group. It cannot confirm U1 understood, agreed to, or took folk watch.",
"Confirm the 23:26 old-bound-threshold crossing. It still cannot confirm the leaver then actually held the tally.",
"Only a conditional coincidence is formed: if the tally was actually held and there was no next hand, the first report falls in the third-night window. The start premise and extra causation are not confirmed.",
"QC-447 only submits advice. The project's responsible agency authorizes separately. A handling receipt forms only after authorized handlers execute.",
]
print("EN3", len(EN3))
