#!/usr/bin/env python3
"""English localization pass for Mountain-Garrison Compact: Ninth Visitor."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path("/Users/Zhuanz/Desktop/新游戏英文版/镇山契")
HTML = ROOT / "相关素材与可玩版" / "镇山契_第九位到访者_v0_3_真实网页与可视证据版.html"
MAP_PATH = ROOT / "_loc" / "en_map.json"

SVG_RE = re.compile(r"data:image/svg\+xml;base64,[A-Za-z0-9+/=]+")
HAN_RE = re.compile(r"[\u4e00-\u9fff]")

SEARCH_BLOCK_NEW = '''  const searchKeywords = Object.freeze([
    Object.freeze({ queries: Object.freeze(["阿山", "槐树村", "AShan", "Huaishu"]), siteId: "forum", opens: Object.freeze(["FORUM-T4098"]) }),
    Object.freeze({ queries: Object.freeze(["第九个", "Ninth"]), siteId: "forum", opens: Object.freeze(["FORUM-T4612"]) }),
    Object.freeze({ queries: Object.freeze(["冰块", "IceBlock"]), siteId: "forum", opens: Object.freeze(["FORUM-T5220"]) }),
    Object.freeze({ queries: Object.freeze(["源码", "管理员密码", "SourceCode", "AdminPassword"]), siteId: "*", opens: Object.freeze(["EX-FORBIDDEN"]), forbidden: true }),
    Object.freeze({ queries: Object.freeze(["阿山", "唯一行为人", "AShan", "SoleActor"]), siteId: "archive", opens: Object.freeze(["ARC-IDX-XGA98"]) }),
    Object.freeze({ queries: Object.freeze(["底片袋", "迁移", "NegBag", "Migration"]), siteId: "archive", opens: Object.freeze(["ARC-BOX-MAP"]) }),
    Object.freeze({ queries: Object.freeze(["正殿", "MainHall"]), siteId: "archive", opens: Object.freeze(["ARC-ENTRY-98"]) }),
    Object.freeze({ queries: Object.freeze(["轮灯", "守更", "WheelLamp", "NightWatch"]), siteId: "folk", opens: Object.freeze(["FOLK-1964-LAMP"]) }),
    Object.freeze({ queries: Object.freeze(["覆写", "Overwrite"]), siteId: "folk", opens: Object.freeze(["FOLK-1974-LATE"]) }),
    Object.freeze({ queries: Object.freeze(["底片袋", "底片", "NegBag", "Negatives"]), siteId: "news", opens: Object.freeze(["NEWS-BF11"]) }),
    Object.freeze({ queries: Object.freeze(["三宿", "ThreeNights"]), siteId: "news", opens: Object.freeze(["NEWS-1982-NIGHT"]) }),
    Object.freeze({ queries: Object.freeze(["滑坡", "北坡", "Landslide", "NorthSlope"]), siteId: "geology", opens: Object.freeze(["GEO-SLIDE-1998"]) }),
    Object.freeze({ queries: Object.freeze(["旧庙", "OldTemple"]), siteId: "geology", opens: Object.freeze(["GEO-PLAN-OLD"]) }),
  ]);'''

CLASSIFY_NEW = '''  function classifyHanWord(value) {
    const raw = String(value == null ? "" : value).trim();
    if (!raw) {
      return { ok: false, kind: "empty", query: "", msg: "Enter one search word." };
    }
    if (/[\\s\\u3000]/.test(raw)) {
      return { ok: false, kind: "multi", query: raw, msg: "Search one word at a time." };
    }
    if (!/^([\\u4e00-\\u9fff]+|[A-Za-z][A-Za-z0-9]*)$/.test(raw)) {
      return { ok: false, kind: "invalid", query: raw, msg: "Use a single word already on an opened page. Spaces and symbols will not hit a record." };
    }
    return { ok: true, kind: "ok", query: raw, msg: "" };
  }'''

SEARCH_RECORDS_LOOKUP_OLD = '''    (WORLD.searchKeywords || []).forEach((row) => {
      if (!row.queries.includes(q)) return;'''

SEARCH_RECORDS_LOOKUP_NEW = '''    const n = String(q).toLowerCase();
    (WORLD.searchKeywords || []).forEach((row) => {
      if (!(row.queries || []).some((item) => String(item).toLowerCase() === n)) return;'''

NAME_VALUES = [
    ("赵成海", "ZhaoChenghai"),
    ("刘庆余", "LiuQingyu"),
    ("张大福", "ZhangDafu"),
    ("李有业", "LiYouye"),
    ("周守义", "ZhouShouyi"),
    ("孙桂兰", "SunGuilan"),
    ("林青", "LinQing"),
    ("巡查员", "PatrolClerk"),
    ("方小禾", "FangXiaohe"),
    ("邓梅", "DengMei"),
    ("许有生", "XuYousheng"),
    ("林文", "LinWen"),
    ("阿山", "AShan"),
]

CSS_ARTIFACT = """
.zh-artifact[lang="zh-Hans"] {
  font-weight: 600;
}
.artifact-translation {
  margin-left: 0.35em;
  font-size: 0.92em;
  opacity: 0.88;
}
.artifact-translation::before { content: "("; }
.artifact-translation::after { content: ")"; }
"""

# Template-only phrases that never appear as standalone quoted WORLD copy.
EXTRA = [
    ("跳到主要内容", "Skip to main content"),
    ("正在打开本地复核工作台……", "Opening the local QC workbench…"),
    ("本原型需要浏览器启用 JavaScript；所有文件均在本地运行，不访问外部网络。", "This prototype needs JavaScript. All files run locally and do not reach the network."),
    ("交接栏：________________　日期：________", "Handover line: ________________  Date: ________"),
    ("本轮回执", "This-round receipt"),
    ("来源记录", "Source record"),
    ("槐县历史专卷数字化复核", "Huaixian historical special-file digital QC"),
    ("《镇山契：第九位到访者》v0.3 离线中文网页档案复核原型。", "Mountain-Garrison Compact: Ninth Visitor v0.3. Offline records-QC prototype."),
    ("镇山契：第九位到访者｜虚构可玩原型", "Mountain-Garrison Compact: Ninth Visitor | fictional playable prototype"),
    ("一次一个汉字词", "One word at a time"),
    ("输入目录字段", "Enter a catalog field"),
    ("输入题名、异名或地名", "Enter a title, variant name, or place"),
    ("如：1982-07-19 或 第4版", "e.g. 1982-07-19 or page 4"),
    ("输入资料编号、地名或年份", "Enter a report ID, place, or year"),
    ("换一个已读页上的汉字词。", "Try another word from a page you already read."),
    ("站内检索完成：", "Site search finished: "),
    ("请输入一个汉字词。", "Enter one search word."),
    ("本机复核会话已建立。工作台未接触任何原物。 ", "Local QC session started. The workbench has not touched any original."),
    ("第${result.level}级提示已展开。", "Hint level ${result.level} is open."),
    ("第4级直接答案已展开；系统没有自动提交。 ", "Level-4 direct answer is open; nothing was auto-submitted. "),
    ("页内参见已加入本机核对；它不改变当前工单前置。 ", "In-page see-also is on this local check. It does not change the current work-order gates. "),
    ("本页普通字段已摘录；请回到参见核对页。 ", "Ordinary fields from this page are excerpted. Return to the see-also check. "),
    ("从交接单抽出一个汉字词", "Pull one word from the handover sheet"),
    ("第一词就在工单里：把「阿山」原样送进槐水人家检索。打开那条帖后，再抽下一词去档案目录。回单仍在，但现在还没到填表的时候。",
     "The first word is already on the sheet: send AShan into Huaishui Locals as a single token. Open that thread, then pull the next word into the archive catalog. The return form is still there; it is not fill-in time yet."),
    ("打开槐水人家", "Open Huaishui Locals"),
    ("先搜「阿山」", "Search AShan first"),
    ("先搜阿山再回单", "Search AShan before the return form"),
    ("先搜词再回单", "Search first, form later"),
    ("搜已读页上的词", "Search a word from a page you already read"),
    ("抽出一个汉字词", "Pull one word"),
    ("站内检索打开来源", "Search a public site and open the source"),
    ("终局才交回单", "File the return only at the end"),
    ("你的身份", "Your role"),
    ("你的权限", "Your authority"),
    ("交接事项", "Handover item"),
    ("访问类型", "Access type"),
    ("复核工单", "QC work order"),
    ("会话状态", "Session state"),
    ("尚未建立", "Not started"),
    ("离线只读原型", "Offline read-only prototype"),
    ("现实使用说明", "Live-use notice"),
    ("先确认内容与专业边界", "Confirm content and professional bounds first"),
    ("展开具体主题", "Expand topic list"),
    ("项目内交接", "In-project handover"),
    ("进入工作台后的三步操作", "Three steps after you enter the workbench"),
    ("阅读数字副本、建立参见与纠错建议；不接触原物，不批准处置，不认定行为人或守者。",
     "Read approved digital copies, build see-also links and correction advice. Do not touch originals, do not approve disposition, and do not name an actor or a folk guardian."),
    ("核对底片袋B归属，并解释“正殿5人、登记8人、急救残句又一个”的口径冲突。",
     "Check where NegBag B is attached, and explain the count clash: MainHall 5, registered 8, and an emergency remnant that adds one more."),
    ("本作完全离线运行；不会请求真实姓名、位置、账号、摄像头、麦克风或网络。",
     "This work runs fully offline. It will not ask for a real name, location, account, camera, microphone, or network."),
    ("当前只供离线试玩；档案与文物保护流程未完成外部专业审查，不能据此执行现实处置。",
     "Offline play only. Archive and heritage procedure has not had outside professional review. Do not run a live disposition from this prototype."),
    ("版本与现实专业边界", "Version and live professional bounds"),
    ("清除本机复核会话？", "Clear this local QC session?"),
    ("这会移除本机的核对回单、提示、相关记录链和本轮结论。公开网页内容不会改变。",
     "This removes local check forms, hints, see-also chains, and this-round conclusions. Public pages do not change."),
    ("取消", "Cancel"),
    ("清除本机复核会话并重新开始", "Clear local QC session and start over"),
    ("卷宗质检工作台", "Records QC workbench"),
    ("工号", "Staff ID"),
    ("工单", "Work order"),
    ("权限", "Authority"),
    ("只读数字副本", "Read-only digital copies"),
    ("工作台工具栏", "Workbench toolbar"),
    ("在办工单", "Open work order"),
    ("数字副本核对", "Digital-copy check"),
    ("来源访问留痕", "Source-visit trail"),
    ("业务步骤", "Business steps"),
    ("业务步骤树", "Business-step tree"),
    ("领取工单", "Take the work order"),
    ("已领取", "Taken"),
    ("来源核对", "Source check"),
    ("当前办理", "In progress"),
    ("保存回单", "Save the return"),
    ("逐项形成", "Built item by item"),
    ("机构处理", "Agency handling"),
    ("与个人建议分离", "Kept apart from personal advice"),
    ("当前队列", "Current queue"),
    ("当前工单队列", "Current work-order queue"),
    ("已进入的参见核对", "See-also checks entered"),
    ("在办件", "Active file"),
    ("经办人", "Handler"),
    ("办理状态", "Handling status"),
    ("等待回执", "Waiting on a receipt"),
    ("来源核对中", "Source check in progress"),
    ("项目队列有一条待取回记录", "The project queue has one record waiting to be taken"),
    ("先读取项目新回执", "Read the new project receipt first"),
    ("每次只取回一条；读完后，工作台才会显示下一项核对。", "Take one at a time. The next check shows only after you finish reading."),
    ("读取一条项目新回执", "Read one new project receipt"),
    ("最近形成的核对回单", "Latest check returns"),
    ("尚未形成回单。先打开当前复核面板。", "No return yet. Open the current check panel first."),
    ("公开站点", "Public sites"),
    ("已打开来源", "Sources opened"),
    ("同批普通工单", "Ordinary jobs in the same batch"),
    ("搜中并打开来源后，会在这里保留访问记录。", "Hits you open stay here as a visit trail."),
    ("当前操作会写入本机会话；不改写公开网页与原始卷宗。", "This action writes the local session. It does not rewrite public pages or original files."),
    ("先读取项目回执", "Read the project receipt first"),
    ("队列暂停", "Queue paused"),
    ("待检索", "Awaiting search"),
    ("当前待核", "Current check"),
    ("执行回执", "Execution receipt"),
    ("本轮明确回执", "This-round explicit receipt"),
    ("本轮现实执行已完成", "This-round live execution is complete"),
    ("查看本轮明确回执", "View this-round explicit receipt"),
    ("打开明确终点", "Open the explicit endpoint"),
    ("打开当前复核面板", "Open the current check panel"),
    ("项目负责人回执读毕后，本轮获准材料核对到此结束。", "After the project-lead receipt is read, this round's approved-material check ends."),
    ("工单已结束，站点可复查", "Work order closed; sites remain reviewable"),
    ("可复查旧帖", "Old threads remain reviewable"),
    ("查看本轮回执", "View this-round receipt"),
    ("继续办理当前项", "Continue the current item"),
    ("资料链已闭合", "This source chain is closed"),
    ("已查看部分记录", "Some records already viewed"),
    ("公开记录可查", "Public records are searchable"),
    ("请选择", "Select"),
    ("请选择事件", "Select an event"),
    ("第${index + 1}位", "Place ${index + 1}"),
    ("逐位选择；重复或缺项不会通过。", "Pick each place. Repeats or gaps will not pass."),
    ("展开第${level + 1}级提示", "Open hint level ${level + 1}"),
    ("请求第4级直接答案", "Request the level-4 direct answer"),
    ("第4级会显示完整可执行答案，但不会自动提交。", "Level 4 shows a full executable answer. It does not auto-submit."),
    ("再次确认并显示", "Confirm again and show"),
    ("四级提示已全部展开。", "All four hint levels are open."),
    ("分级提示（已展开 ${level}/4）", "Graded hints (${level}/4 open)"),
    ("打开来源核对材料；来源页会直接返回这里。仅打开不会自动完成本项。",
     "Open the source materials. Source pages return here. Opening a page does not finish this item by itself."),
    ("核对类型 · ", "Check type · "),
    ("返回工作台", "Return to workbench"),
    ("当前工单只读", "Current work order is read-only"),
    ("前一屏尚未保存", "The previous screen is not saved"),
    ("来源仍可浏览，但核对回单必须按可见操作逐屏保存。", "Sources stay browsable, but check returns must be saved screen by screen with visible actions."),
    ("回到当前面板", "Return to the current panel"),
    ("当前访问边界", "Current access bound"),
    ("公开来源仍可直接浏览；核对回单按已保存的分屏顺序形成。", "Public sources stay directly readable. Check returns follow the saved split-screen order."),
    ("本面板已保存。", "This panel is saved."),
    ("进入下一面板", "Go to the next panel"),
    ("查看机构处理状态", "View agency handling status"),
    ("查看本项回单", "View this item's return"),
    ("并返回工作台", " and return to the workbench"),
    ("查看前一屏", "View previous screen"),
    ("本项步骤", "Steps for this item"),
    ("打开本项来源", "Open this item's sources"),
    ("回来填写", "Return and fill in"),
    ("保存本项回单", "Save this item's return"),
    ("当前材料", "Current material"),
    ("核对提示", "Check cue"),
    ("保存后留下的问题", "Question left after save"),
    ("处置建议尚未提交", "Disposition advice not yet submitted"),
    ("返回建议屏幕", "Return to the advice screen"),
    ("你的处置建议：方案", "Your disposition advice: Plan "),
    ("建议已记录，机构授权回执尚未读取", "Advice is recorded. The agency authorization receipt is not yet read."),
    ("QC-447没有批准权限。下面的操作只读取项目责任机构独立形成的授权回执，不代表经办人批准。",
     "QC-447 has no approval power. The control below only reads an authorization receipt formed independently by the responsible agency. It is not a handler approval."),
    ("读取项目责任机构授权回执", "Read the responsible agency's authorization receipt"),
    ("你的建议：方案", "Your advice: Plan "),
    (" · 机构授权：方案", " · agency authorization: Plan "),
    ("项目责任机构已授权同一方案", "The responsible agency has authorized the same plan"),
    ("已进入受权经办队列。下面的操作只读取执行记录。", "is in the authorized-handler queue. The control below only reads the execution record."),
    ("读取受权经办人员执行回执", "Read the authorized handler's execution receipt"),
    ("受权经办人员执行：方案", "Authorized-handler execution: Plan "),
    (" · 已完成", " · complete"),
    ("项目负责人回执已读，本轮处理回执已形成", "Project-lead receipt is read. This-round handling receipt is formed."),
    ("打开完整处理回执", "Open the full handling receipt"),
    ("项目负责人尚有一条最终回执", "The project lead still has one final receipt"),
    ("请返回项目工作台读取回执，再打开完整处理回执。", "Return to the project workbench, read the receipt, then open the full handling receipt."),
    ("返回项目工作台", "Return to the project workbench"),
    ("这一项核对完了什么", "What this check recorded"),
    ("项目处理状态", "Project handling status"),
    ("来源核对、建议、授权与执行", "Source check, advice, authorization, and execution"),
    ("建议与批准分离", "Advice kept apart from approval"),
    ("受权经办人员执行", "Authorized-handler execution"),
    ("返回核对材料", "Return to check materials"),
    ("返回查看三件来源", "Return to the three source cards"),
    ("返回查看两方案预览", "Return to the two-plan preview"),
    ("进入下一项核对", "Go to the next check"),
    ("返回项目工作台读取新回执", "Return to the workbench for the new receipt"),
    ("本次对照顺序", "Order of this comparison"),
    ("你先封存了第三夜计算，再打开首报进行对照。", "You sealed the third-night calculation first, then opened the first report for comparison."),
    ("你在封存计算前已经看过首报；条件结论仍有效，但本次不计作“先算后看”。",
     "You had already seen the first report before sealing the calculation. The conditional conclusion still holds; this round is not counted as calculate-then-look."),
    ("结构化核对回单", "Structured check return"),
    ("：已保存", ": saved"),
    ("本机核对回单", "Local check return"),
    ("本次核对边界", "Bound of this check"),
    ("仍需追问", "Still to ask"),
    ("后续操作", "Next actions"),
    ("返回查看本项材料", "Return to this item's materials"),
    ("工单队列", "Work-order queue"),
    ("这项核对尚未排到当前工单", "This check is not on the current work order yet"),
    ("已知完整地址仍可打开对应网页；工作台回单按已保存的前置核对顺序形成。",
     "Known full addresses still open their pages. Workbench returns follow the saved prerequisite order."),
    ("回到当前待核项", "Return to the current check"),
    ("字段已记入这条参见核对", "Fields are logged on this see-also check"),
    ("提交有限排除", "Submit the limited exclusion"),
    ("页内参见核对", "In-page see-also check"),
    ("随时离开这条记录链，继续主工单", "Leave this record chain at any time and continue the main work order"),
    ("不改变当前工单前置", "Does not change current work-order gates"),
    ("为什么这条连接值得核对", "Why this connection is worth checking"),
    ("开始沿页内参见核对", "Start the in-page see-also check"),
    ("下一份来源", "Next source"),
    ("打开来源页面", "Open the source page"),
    ("这条连接如何闭合", "How this connection closes"),
    ("方法：", "Method: "),
    ("边界：", "Bound: "),
    ("有限排除已保存；不进入当前复核前置。", "Limited exclusion saved. It does not enter the current QC gates."),
    ("已打开并摘录的来源", "Sources opened and excerpted"),
    ("尚未把来源字段记入这条参见核对。", "No source fields are logged on this see-also check yet."),
    ("旧帖镜像 · 只读", "Old-thread mirror · read-only"),
    ("论坛首页", "Forum home"),
    ("槐水闲谈", "Huaishui chat"),
    ("乡里问事", "Local asks"),
    ("旧物旧景", "Old things, old views"),
    ("站务公告", "Board notice"),
    ("开放目录", "Open catalog"),
    ("利用说明", "Use notes"),
    ("全宗指南", "Fonds guide"),
    ("数字化公示", "Digitization notice"),
    ("槐档", "HX"),
    ("资料目录", "Holdings list"),
    ("课题组简介", "Team note"),
    ("采风地区", "Collecting area"),
    ("读者补正", "Reader corrections"),
    ("友情链接", "Links"),
    ("数据目录", "Data catalog"),
    ("专题图件", "Thematic drawings"),
    ("监测资料", "Monitoring files"),
    ("资料说明", "File notes"),
    ("主题 / 版面", "Thread / board"),
    ("作者 / 发帖", "Author / posted"),
    ("回复 / 最后回复", "Replies / last reply"),
    ("发帖：", "Posted: "),
    ("最后回复：", "Last reply: "),
    ("回复", " replies"),
    ("题名 / 范围", "Title / scope"),
    ("年代", "Date"),
    ("目录字段", "Catalog fields"),
    ("开放级别：目录著录", "Open level: catalog description"),
    ("槐水人家 > 全部版面", "Huaishui Locals > all boards"),
    ("在线 37 · 今日 12帖 · 镜像只读", "Online 37 · today 12 posts · mirror read-only"),
    ("用户登录", "User login"),
    ("用户名", "Username"),
    ("口令", "Password"),
    ("镜像站不可登录", "Mirror login is disabled"),
    ("版面分类", "Board list"),
    ("全部版面", "All boards"),
    ("校友与同乡", "Alumni and hometown"),
    ("2004镜像限制", "2004 mirror limits"),
    ("原站账号、附件与部分最后回复时间未保留。", "Original accounts, attachments, and some last-reply times were not kept."),
    ("搜旧帖", "Search old posts"),
    ("论坛搜索", "Forum search"),
    ("今日", "Today"),
    ("主题", "Threads"),
    ("帖子", "Posts"),
    ("在线", "Online"),
    ("最后整理：2026-07", "Last arranged: 2026-07"),
    ("检索结果：", "Search results: "),
    ("条", ""),
    (" · 关键词“", " · query “"),
    ("Powered by HS-BBS 2.0", "Powered by HS-BBS 2.0"),
    ("镜像内容保持原帖字段", "Mirror keeps original post fields"),
    ("开放目录树", "Open catalog tree"),
    ("▾ 槐县档案开放目录", "▾ Huaixian Archives open catalog"),
    ("　▾ 历史专卷", "　▾ Historical special files"),
    ("　　├ 数字化批次", "　　├ Digitizing batches"),
    ("　　├ 人名与身份", "　　├ Names and identity"),
    ("　　├ 工程与图件", "　　├ Engineering and drawings"),
    ("　　└ 参见目录", "　　└ See-also catalog"),
    ("馆藏统计", "Holdings counts"),
    ("目录记录", "Catalog records"),
    ("正文开放", "Body open"),
    ("依记录", "Per record"),
    ("责任者", "Creator"),
    ("可检索", "Searchable"),
    ("开放状态", "Open status"),
    ("逐条显示", "Shown per record"),
    ("目录筛选与开放状态说明", "Catalog filters and open-status notes"),
    ("可按题名、年代、责任者、工作号检索。目录命中不等于正文开放，也不替代原卷结论。",
     "Search by title, date, creator, or work number. A catalog hit is not an open body, and it does not replace an original-file conclusion."),
    ("开放目录查询", "Open-catalog query"),
    ("题名 / 年代 / 责任者 / 工作号", "Title / date / creator / work number"),
    ("查询目录", "Query catalog"),
    ("排序：档号升序", "Sort: archival number asc."),
    ("每页 20 条", "20 per page"),
    ("目录著录与数字副本开放范围分别记录", "Catalog description and digital-copy open scope are recorded separately"),
    ("返回目录首页", "Return to catalog home"),
    ("全部资料", "All holdings"),
    ("口述与抄本", "Oral notes and copies"),
    ("地方刊物索引", "Local-serial index"),
    ("版本记录", "Version record"),
    ("异名与地名表", "Variant-name and place list"),
    ("页面计数：006741", "Page count: 006741"),
    ("资料题名或异名：", "Holdings title or variant name: "),
    ("查找", "Find"),
    ("本站说明", "Site note"),
    ("异文照录，不替各地说法作统一解释。底本限制与读者补正均保留。",
     "Variants are copied as found. The site does not unify local tellings. Base-text limits and reader corrections are kept."),
    ("新近整理", "Newly arranged"),
    ("旧刊目录补录", "Old-serial catalog addenda"),
    ("来信勘误 12 条", "12 mailed corrections"),
    ("失效链接 7 条", "7 dead links"),
    ("镜像与站务", "Mirrors and desk"),
    ("主站镜像一", "Main-site mirror 1"),
    ("文字版入口", "Text-only entry"),
    ("旧浏览器说明", "Old-browser note"),
    ("本站整理 · 页面计数 006741", "Site compilation · page count 006741"),
    ("部分旧链接可能失效", "Some old links may be dead"),
    ("报纸目录", "Newspaper catalog"),
    ("按日期浏览", "Browse by date"),
    ("版次说明", "Edition notes"),
    ("底片目录", "Negatives catalog"),
    ("OCR校正记录", "OCR correction log"),
    ("日期与版次检索", "Date and edition search"),
    ("关键词 / 日期 / 版次", "Keyword / date / edition"),
    ("检索馆藏", "Search holdings"),
    ("上一个月", "Previous month"),
    ("下一个月", "Next month"),
    ("1982年 6月", "June 1982"),
    ("日期索引", "Date index"),
    ("日", "Su"),
    ("一", "Mo"),
    ("二", "Tu"),
    ("三", "We"),
    ("四", "Th"),
    ("五", "Fr"),
    ("六", "Sa"),
    ("当日版次", "That day's editions"),
    ("第1版 要闻", "p.1 News"),
    ("第2版 地方", "p.2 Local"),
    ("第3版 生产", "p.3 Production"),
    ("第4版 社会", "p.4 Society"),
    ("可按日期浏览整版；OCR命中不替代影像核对。", "Browse whole pages by date. An OCR hit does not replace image check."),
    ("馆藏影像", "Holdings image"),
    ("日期 → 版次 → 整版影像 → OCR分栏", "Date → edition → whole-page image → OCR columns"),
    ("OCR可能把人名、地名和数字识别错误，请以整版影像为准。", "OCR may misread names, places, and numbers. Use the whole-page image."),
    ("馆藏影像、OCR文字与校正记录分层保存", "Holdings image, OCR text, and correction log are stored in layers"),
    ("返回报纸目录", "Return to newspaper catalog"),
    ("资料分类", "File classes"),
    ("全部数据", "All data"),
    ("基础地质", "Basic geology"),
    ("工程勘察", "Engineering survey"),
    ("雨量监测", "Rainfall monitoring"),
    ("闭坑资料", "Mine-closure files"),
    ("坡体巡查", "Slope patrol"),
    ("地图工具", "Map tools"),
    ("平移", "Pan"),
    ("量距", "Measure"),
    ("图层", "Layers"),
    ("打开带图件的记录后启用。", "Enabled after a record with drawings is opened."),
    ("数据范围、坐标与高程筛选", "Data extent, coordinate, and elevation filters"),
    ("叠加不同年代资料前，先核对坐标系、高程基准和调查范围。标题相近不是空间贯通。",
     "Before overlaying files from different years, check coordinate system, elevation datum, and survey extent. Similar titles are not spatial continuity."),
    ("资料编号 / 坐标 / 年份", "File ID / coordinate / year"),
    ("检索数据", "Search data"),
    ("资料类型", "File type"),
    ("报告", "Reports"),
    ("附件", "Attachments"),
    ("图件", "Drawings"),
    ("监测表", "Monitor sheets"),
    ("目录开放", "Catalog open"),
    ("数字附件", "Digital attachments"),
    ("报告与附件合并显示", "Reports and attachments shown together"),
    ("坐标、高程基准和调查范围须随记录核对", "Coordinate, elevation datum, and survey extent must be checked with the record"),
    ("返回数据目录", "Return to data catalog"),
    ("没有匹配记录", "No matching records"),
    ("此文件已被禁止访问", "This file is forbidden"),
    ("旧帖镜像", "Old-thread mirror"),
    ("版面：", "Board: "),
    ("编辑记录：", "Edit log: "),
    ("—— 从旧帖镜像恢复的可见正文", "—— visible body restored from the old-thread mirror"),
    ("编辑", "Edit"),
    ("引用", "Quote"),
    ("镜像内不可用", "Unavailable in the mirror"),
    ("系统镜像员", "System mirror clerk"),
    ("只读", "Read-only"),
    ("镜像说明", "Mirror note"),
    ("版面", "Board"),
    ("回复数", "Reply count"),
    ("最后回复", "Last reply"),
    ("主题已锁定", "Thread locked"),
    ("返回", "Return to "),
    ("主题列表", " thread list"),
    ("目录层级", "Catalog levels"),
    ("返回开放目录", "Return to open catalog"),
    ("槐县历史专卷", "Huaixian historical special files"),
    ("数字化移交批次", "Digitizing transfer batch"),
    ("开放层级：目录", "Open level: catalog"),
    ("正文状态：以字段为准", "Body status: as in the fields"),
    ("目录记录只陈述开放字段；请按来源限制使用。", "Catalog records state open fields only. Use them inside the source limits."),
    (" / 全宗 / 案卷 / ", " / fonds / file / "),
    ("长结果字段", "Long result fields"),
    ("范围与内容说明", "Scope and content note"),
    ("当前页为目录著录详情", "This page is a catalog-description detail"),
    ("资料栏目", "Holdings columns"),
    ("返回目录", "Return to list"),
    ("采风抄本", "Field copies"),
    ("本站整理，异文照录", "Site compilation; variants copied as found"),
    ("页面计数：006741", "Page count: 006741"),
    ("站务与索引", "Desk and index"),
    ("本月新增目录", "This month's new catalog"),
    ("异名对照表", "Variant-name table"),
    ("读者补正簿", "Reader correction book"),
    ("旧站镜像入口", "Old-site mirror entry"),
    ("链接失效请按题名返回目录检索。", "If a link is dead, search the catalog by title."),
    (" · 异文与限制照录", " · variants and limits copied as found"),
    ("底本说明", "Base-text note"),
    ("返回底片目录", "Return to negatives catalog"),
    ("底片帧", "Negative frames"),
    ("摄影日志", "Photo log"),
    ("底片目录记录", "Negatives catalog record"),
    ("底片影像与摄影日志并列核对", "Negative image and photo log checked side by side"),
    ("槐县报刊／底片数字化影像", "Huaixian press / negatives digital image"),
    ("摄影日志与底片字段", "Photo-log and negative fields"),
    ("底片帧只按摄影日志、齿孔连续性和可见方向陈述，不补认人物身份。",
     "Frames are stated from the photo log, perforation continuity, and visible direction. They do not fill in a person's identity."),
    ("返回日期/版次检索", "Return to date/edition search"),
    ("整版影像", "Whole-page image"),
    ("版次目录", "Edition catalog"),
    ("OCR文字", "OCR text"),
    ("报纸整版记录", "Newspaper whole-page record"),
    ("日期、版次与OCR分层显示", "Date, edition, and OCR shown in layers"),
    ("槐县旧报整版", "Huaixian old-paper whole page"),
    ("版次与OCR元数据", "Edition and OCR metadata"),
    ("OCR只用于检索；报纸发行、缩微载体与文字校正字段分别记录。",
     "OCR is for search only. Issue, microfilm carrier, and text-correction fields are recorded separately."),
    ("报纸整版目录", "Newspaper whole-page catalog"),
    ("返回OCR校正记录", "Return to OCR correction log"),
    ("修订前后", "Before / after"),
    ("校正日志", "Correction log"),
    ("影像状态", "Image status"),
    ("文字修订与原影像状态分开记录", "Text revision and original-image status are recorded apart"),
    ("文字识别修订日志", "OCR revision log"),
    ("修订前", "Before"),
    ("修订后", "After"),
    ("校正与影像日志", "Correction and image log"),
    ("校正时间", "Correction time"),
    ("影像是否改变", "Image changed?"),
    ("日志摘要", "Log summary"),
    ("OCR字段用于检索；校正日志不替换原始影像。", "OCR fields are for search. The correction log does not replace the original image."),
    ("返回数据目录", "Return to data catalog"),
    ("技术报告", "Technical report"),
    ("报告附件", "Report attachments"),
    ("坐标与高程", "Coordinates and elevation"),
    ("调查范围", "Survey extent"),
    ("图件工具", "Drawing tools"),
    ("坐标", "Coords"),
    ("只读记录页；工具状态随附件提供。", "Read-only record page. Tool state follows the attachment."),
    ("记录编号：", "Record ID: "),
    (" / 技术报告 / ", " / technical report / "),
    ("报告与附件", "Report and attachments"),
    ("主报告", "Main report"),
    ("资料日期", "File date"),
    ("来源状态", "Source status"),
    ("技术字段", "Technical fields"),
    ("记录摘要", "Record abstract"),
    ("本页按记录范围陈述；空数据与不在范围均不作因果推断。",
     "This page states what is in scope. Empty data and out-of-scope items are not causal findings."),
    ("当前页为技术资料记录", "This page is a technical-file record"),
    ("表格目录 · 只读", "Table catalog · read-only"),
    ("字段型附件", "Field-type attachment"),
    ("表格目录", "Table catalog"),
    ("平面方位 · 只读", "Plan / bearing · read-only"),
    ("位置与方向附件", "Position and direction attachment"),
    ("平面方位", "Plan / bearing"),
    ("时间线事件 · 只读", "Timeline events · read-only"),
    ("事件顺序附件", "Event-order attachment"),
    ("时间线事件", "Timeline events"),
    ("波形媒体 · 只读", "Waveform media · read-only"),
    ("媒体转写附件", "Media-transcript attachment"),
    ("波形媒体", "Waveform media"),
    ("实物痕迹 · 只读", "Physical traces · read-only"),
    ("痕迹观察附件", "Trace-observation attachment"),
    ("实物痕迹", "Physical traces"),
    ("方案流程 · 只读", "Plan workflow · read-only"),
    ("候选流程预览", "Candidate-workflow preview"),
    ("方案流程", "Plan workflow"),
    ("只读附件", "read-only attachment"),
    ("访问范围：当前工单获准数字副本", "Access: approved digital copies for the current work order"),
    ("使用边界", "Use bound"),
    ("原物未接触。", "Originals were not touched."),
    ("QC-447只核对屏幕上的获准数字副本；没有移动、接收或处置任何真实原物。空白字段保持空白，不用推测补齐。",
     "QC-447 only checks approved digital copies on screen. No real original was moved, received, or disposed of. Blank fields stay blank. Do not fill them by guess."),
    ("项目执行回执", "Project execution receipt"),
    ("最终回执尚未形成", "Final receipt is not yet formed"),
    ("回执状态：等待", "Receipt status: waiting"),
    ("你实际核完的可选排除", "Optional exclusions you actually closed"),
    ("：这条说法已经对不上", ": this claim no longer fits"),
    ("项目执行回执 · 方案", "Project execution receipt · Plan "),
    ("本轮复核已经结束", "This-round QC is finished"),
    ("返回已完成工单", "Return to the completed work order"),
    ("回执状态：已形成", "Receipt status: formed"),
    ("工单状态", "Work-order status"),
    ("已提交并完成本轮复核", "Submitted; this-round QC complete"),
    ("所选处置", "Chosen disposition"),
    ("现实执行", "Live execution"),
    ("已完成", "Complete"),
    ("原始卷宗", "Original files"),
    ("未改写", "Not rewritten"),
    ("未决问题", "Unresolved questions"),
    ("可展开", "Expandable"),
    ("本章结束", "Chapter end"),
    ("当前获准材料已核对完毕", "Approved materials for this round are checked"),
    ("受权经办人员执行记录", "Authorized-handler execution record"),
    ("职业边界：", "Professional bound: "),
    ("两类处置均不改变的核对边界", "Check bounds neither disposition changes"),
    ("旧索引的唯一行为人连接不成立；三名儿童已经分别还名；自然机制充分。儿童死亡责任、契是否受纳或退止、以及额外超自然因果均没有被现有材料确认或证伪。",
     "The old-index SoleActor link is ruled out. The three children have been renamed separately. Natural mechanism is sufficient. Child-death responsibility, whether the compact was received or withdrawn, and extra supernatural causation are not established by these sources, and they are not disproved either."),
    ("展开仍未决的问题", "Expand questions still unresolved"),
    ("404 / 未收录", "404 / not listed"),
    ("这个地址没有对应的公开记录", "This address has no matching public record"),
    ("返回安全入口", "Return to a safe entry"),
    ("数字资源质量复核", "Digital-resource quality QC"),
    ("访问说明", "Access note"),
    ("尚未建立复核会话", "QC session not started"),
    ("QC-447 · 外部来源", "QC-447 · outside source"),
    ("返回当前复核项", "Return to current check"),
    ("返回访问说明", "Return to the access note"),
    ("复核浏览会话", "QC browsing session"),
    ("当前复核项", "Current check"),
    ("相关记录核对", "Related-record check"),
    ("地址未收录", "Address not listed"),
    ("核对记录", "Check record"),
    ("一条相关记录连接", "A related-record link"),
    ("影像未提供", "Image not supplied"),
    ("本地副本只有目录与文字字段。", "The local copy has catalog and text fields only."),
    ("未提供可核对的原始影像；本页不会用装饰性示意图代替证据。",
     "No checkable original image is supplied. This page will not replace evidence with a decorative diagram."),
    ("图像等价说明：", "Image-equivalent note: "),
    ("本页已打开", "This page is open"),
    ("摘录到《", "Excerpt into “"),
    ("沿页内参见继续核对", "Continue along the in-page see-also"),
    ("当前仅使用内存存档。", "This session is memory-only."),
    ("浏览器未提供本机存档；本次会话仍可继续，但关闭页面后不会保留。",
     "This browser has no local storage. The session can continue, but it will not keep after the page closes."),
    ("打开‘本项来源’，核对材料。", "Open “This item's sources” and check the material."),
    ("回到当前复核项填写。", "Return to the current check and fill in."),
    ("保存本项回单，进入下一屏或查看回单。", "Save this item's return, then go to the next screen or view the return."),
    ("这份记录已看过，标为已读并继续", "This record is already viewed. Mark read and continue"),
    ("项目内新回执", "New in-project receipt"),
    ("留在工作台并标为已读", "Stay on the workbench and mark read"),
    ("项目回执", "Project receipt"),
    ("展开文字等价视图与版本转写", "Open text-equivalent view and version transcript"),
    ("展开波形文字等价视图与转写", "Open waveform text-equivalent view and transcript"),
    ("展开方位图文字等价视图", "Open plan text-equivalent view"),
    ("展开痕迹图文字等价视图", "Open trace-diagram text-equivalent view"),
    ("展开附件文字等价视图", "Open attachment text-equivalent view"),
    ("展开报告文字等价视图", "Open report text-equivalent view"),
    ("展开底片文字等价视图", "Open negative text-equivalent view"),
    ("展开OCR文字等价视图", "Open OCR text-equivalent view"),
    ("查看范围说明的文字等价视图", "View the scope-note text equivalent"),
    ("查看文字等价视图与转写", "View text equivalent and transcript"),
    ("同件另挂 · 原件见民俗站《", "Same object, other hanging · original at the folk site “"),
    ("同件另挂 · 原件见附件《", "Same object, other hanging · original in attachment “"),
    ("同件另挂 · 原件见旧报《", "Same object, other hanging · original in the old paper “"),
    ("记录所属站点不存在。", "This record's site does not exist."),
    ("这个站点不存在。", "This site does not exist."),
    ("没有这项核对记录。", "There is no such check record."),
    ("原字段未著录", "Original field not described"),
    ("否", "no"),
    ("是", "yes"),
    ("来源", "Source"),
    ("使用边界", "Use bound"),
    ("状态", "Status"),
    ("页数", "Pages"),
    ("地点", "Place"),
    ("时间", "Time"),
    ("年份", "Year"),
    ("姓名", "Name"),
    ("身份", "Identity"),
    ("位置", "Position"),
    ("路径", "Route"),
    ("资料类型", "File type"),
    ("事项", "Item"),
    ("报告编号", "Report ID"),
    ("开放范围", "Open scope"),
    ("材质", "Material"),
    ("数量", "Quantity"),
    ("相关人员", "Related person"),
    ("记录角色", "Recorded role"),
    ("底片号", "Negative no."),
    ("图层", "Layer"),
    ("记录结论", "Recorded conclusion"),
    ("时区", "Timezone"),
    ("修订前", "Before revision"),
    ("修订后", "After revision"),
    ("补正记录", "Correction record"),
    ("整理者", "Arranger"),
    ("来源链", "Source chain"),
    ("比例尺", "Scale"),
    ("特征摘要", "Trait summary"),
    ("保管记录", "Custody record"),
    ("记录原因", "Recorded reason"),
    ("对象", "Object"),
    ("编号", "Number"),
    ("当前状态", "Current status"),
    ("发现记录", "Find record"),
    ("封识状态", "Seal status"),
    ("扫描状态", "Scan status"),
    ("纸张状态", "Paper status"),
    ("卷袋标识", "Bag mark"),
    ("问题记录", "Issue record"),
    ("校验范围", "Hash scope"),
    ("镜像状态", "Mirror status"),
    ("镜像范围", "Mirror scope"),
    ("主题性质", "Topic type"),
    ("原版面", "Original board"),
    ("存档时间", "Archive time"),
    ("原卷号", "Original file no."),
    ("数字化批次", "Digitizing batch"),
    ("时间范围", "Time window"),
    ("出生年份", "Birth year"),
    ("登记住址", "Registered address"),
    ("连续性说明", "Continuity note"),
    ("目录分区", "Catalog section"),
    ("到访记录", "Visit record"),
    ("版本号", "Version ID"),
    ("替代版本", "Supersedes"),
    ("夜次口径", "Night-count rule"),
    ("一周起算", "Week start"),
    ("录音带数", "Tape count"),
    ("补正状态", "Correction status"),
    ("底片条号", "Strip no."),
    ("帧范围", "Frame range"),
    ("参照材料", "Read with"),
    ("胶片编号", "Film no."),
    ("限制条件", "Limit"),
    ("行进方向", "Travel direction"),
    ("报刊名称", "Publication"),
    ("版次", "Edition"),
    ("文字识别状态", "OCR status"),
    ("OCR层", "OCR layer"),
    ("影像是否变更", "Image changed"),
    ("距离", "Distance"),
    ("高程", "Elevation"),
    ("首报时间", "First-report time"),
    ("图面差值", "Plan delta"),
    ("坐标基准", "Coordinate datum"),
    ("测站", "Station"),
    ("道路位置", "Road position"),
    ("图纸套", "Drawing set"),
    ("最大可达外缘", "Max reach edge"),
    ("封识", "Seal"),
    ("头部区域", "Head zone"),
    ("颈部区域", "Neck zone"),
    ("拖曳痕迹", "Drag traces"),
    ("延伸工具", "Extension tool"),
    ("定位点甲", "Anchor A"),
    ("定位点乙", "Anchor B"),
    ("背景参照", "Background ref."),
    ("卡片组", "Card set"),
    ("人员标记", "Actor labels"),
    ("门杠", "Door bar"),
    ("门销", "Door pin"),
    ("绳索", "Cord"),
    ("门体", "Door body"),
    ("纤维", "Fiber"),
    ("擦痕", "Scratch"),
    ("延迟", "Delay"),
    ("融水", "Meltwater"),
    ("修补线", "Repair thread"),
    ("药袋", "Medicine bag"),
    ("断口", "Break"),
    ("排列顺序", "Order"),
    ("逐日连续性", "Day-by-day continuity"),
    ("识别特征", "Identifying trait"),
    ("登记表对应", "Register match"),
    ("亲属关系", "Kin relation"),
    ("失踪时间窗", "Missing window"),
    ("就诊对象", "Patient"),
    ("暗板接触", "Hidden-panel contact"),
    ("门销接触", "Door-pin contact"),
    ("23:26离开记录", "23:26 exit record"),
    ("门外落杠", "Outside bar drop"),
    ("成人死亡范围", "Adult-death scope"),
    ("儿童身份材料", "Child identity material"),
    ("最后可核时间", "Last checkable time"),
    ("原官方说法", "Original official account"),
    ("收件回执", "Incoming receipt"),
    ("领取存根", "Pickup stub"),
    ("匿名单元", "Anonymous unit"),
    ("亲缘材料", "Kin material"),
    ("医院记录", "Hospital record"),
    ("卫生室记录", "Clinic record"),
    ("安葬记录", "Burial record"),
    ("寻人启事", "Search notice"),
    ("河道接报", "River reception"),
    ("刻痕", "Notch"),
    ("门槛位置", "Threshold position"),
    ("暗板位置", "Hidden-panel position"),
    ("北坡界", "NorthSlope bound"),
    ("参照点", "Reference points"),
    ("越界时刻", "Crossing time"),
    ("到场状态", "Presence"),
    ("近路假设", "Shortcut hypothesis"),
    ("门闩纤维", "Latch fiber"),
    ("水损红绳", "Flood red cord"),
    ("缺失卷号", "Missing roll"),
    ("暂列缺失", "Provisional missing"),
    ("调阅章", "Borrowing stamp"),
    ("0.86米", "0.86 m"),
    ("距定位点1.43米", "1.43 m from anchor"),
    ("正反面连续", "front/back continuous"),
    ("未见连续拖曳痕", "none continuous"),
    ("清单未列", "not listed"),
    ("未决", "unresolved"),
    ("连续", "continuous"),
    ("无", "none"),
    ("向内开启", "inward-opening"),
    ("旧棉纱／双股接触", "old cotton/double contact"),
    ("轴向", "axial"),
    ("约4秒", "about 4s"),
    ("未记录", "not recorded"),
    ("位于1974层下方", "below 1974 layer"),
    ("不早于1982年", "not-before 1982"),
    ("1998年封存", "sealed 1998"),
    ("1998年新鲜断口", "fresh 1998"),
    ("修补线层＜药袋层＜纸张层＜救援破口", "repair<medicine<paper<rescue break"),
    ("同一匿名特征组U1", "same anonymous profile U1"),
    ("三只独立连续封袋", "three independent continuous bags"),
    ("未确定", "not assigned"),
    ("左足第二趾末节缺失", "left second toe distal segment absent"),
    ("墙后暗板→正殿→门廊", "hidden-panel>hall>porch"),
    ("全身越过门槛", "full-body threshold crossing"),
    ("仅登记一名同父同母兄长林文", "only recorded full brother Lin Wen"),
    ("已确认", "confirmed"),
    ("1971年在校记录", "1971 school attendance"),
    ("1973年在校记录", "1973 school record"),
    ("1974年疫苗卡／最后记录", "1974 vaccine/last record"),
    ("未找到", "not found"),
    ("有记录", "present"),
    ("无法建立", "not established"),
    ("同父同母兄长", "full sibling brother"),
    ("母女", "mother-daughter"),
    ("同父同母姐姐", "full sibling sister"),
    ("东北侧旧刻痕", "north-east old notch"),
    ("东北侧", "north-east"),
    ("人券附件", "human-voucher attachment"),
    ("正殿南门", "south main door"),
    ("旧界以内", "inside boundary"),
    ("图上方为北", "map-up"),
    ("墙后暗板→正殿→南门", "hidden panel>hall>south door"),
    ("已排除", "excluded"),
    ("1998年东柜", "1998 east cabinet"),
    ("2026年北坡封存龛", "2026 north-slope sealed niche"),
    ("新涤棉／右捻", "new polyester-cotton/right twist"),
    ("2卷", "2 rolls"),
    ("1卷", "1 roll"),
    ("22:19—00:05在卫生室", "22:19-00:05 clinic"),
    ("22:16已关闭", "closed 22:16"),
    ("旧棉纱／左捻", "old cotton/left twist"),
    ("涤棉／右捻", "poly-cotton/right twist"),
    ("沙袋领用账已结清", "sandbag ledger closed"),
    ("数字正文", "digital body"),
    ("第118帧", "frame118"),
    ("PingFang SC", "Segoe UI"),
    ("Hiragino Sans GB", "Segoe UI"),
    ("Microsoft YaHei", "Segoe UI"),
    ("普通内容、相邻内容和目标内容共用同一数据结构与视觉权重。", "Ordinary, adjacent, and target content share one data shape and the same visual weight."),
    ("槐北地方文化课题组资料页", "Huaibei local-culture team holdings page"),
    ("离线中文网页档案复核原型。", "Offline web records-QC prototype."),
    ("该面板编号不存在", "That panel ID does not exist"),
    ("本机存档写入失败；当前页面仍保留进度，关闭后可能丢失", "Local save write failed. This page still holds progress; it may be lost on close."),
    ("本机存档无法读取，已在内存中建立安全的新会话；旧内容未被执行", "Local save could not be read. A safe new in-memory session was started. Old content was not run."),
    ("本机复核会话已清除；世界数据没有改变。", "Local QC session cleared. World data did not change."),
    ("精确路由清单中没有这个地址。记录不会使用宽前缀回退", "This address is not on the exact-route list. Records do not fall back to a wide prefix."),
    ("每个工作面板的可见来源清单。来源只控制会话CTA，不是完成资格；每个问题的均显式引用本面板来源，测试据此检查没有隐藏常识答案",
     "Visible source list for each work panel. Sources control session CTAs, not completion. Each question cites this panel's sources; tests use that to check there is no hidden common-sense answer."),
    ("机构授权和受权经办人员执行必须分别记录；直接打开地址不能跳过这些业务节点",
     "Agency authorization and authorized-handler execution must be recorded separately. Opening an address directly cannot skip those business nodes."),
    ("项目内获准数字附件。它们是可打开的网页来源，不以“已读”替代表单操作",
     "In-project approved digital attachments. They are openable web sources. “Already read” does not replace a form action."),
    ("这是分屏检查点，下一屏会继续使用本次核对", "This is a split-screen checkpoint. The next screen will keep using this check."),
    ("结构化核对回单已经写入本机会话", "The structured check return is written to the local session."),
    ("受权经办人员执行已经完成，但项目负责人的最终回执尚未读完。请先返回工作台读取",
     "Authorized-handler execution is complete, but the project lead's final receipt is not yet read. Return to the workbench first."),
    ("一份关于卷号、九个人、三盏灯与一条从未被档案回答的旧界记录",
     "A file about volume numbers, nine people, three lamps, and an old-bound record the archives never answered"),
    ("进入后只按一张工单工作；其他网站从当前复核项内按需打开。",
     "Once inside, work from one work order. Other sites open from the current check as needed."),
    ("QC-447 操作交接单", "QC-447 operating handover sheet"),
    ("查看范围说明的文字等价视图", "View the scope-note text equivalent"),
    ("对照范围", "ComparisonScope"),
    ("对照时点", "ComparisonTime"),
    ("底片身份", "NegativesIdentity"),
    ("系统编号", "SystemNumber"),
    ("核验范围", "CheckScope"),
    ("排除项", "ExclusionItems"),
    ("实际授权", "ActualAuthorization"),
    ("原物经办", "OriginalHandling"),
    ("共同地点", "SharedPlace"),
    ("原物接触", "OriginalContact"),
    ("内容语体", "Register"),
    ("主要读者", "Primary readers"),
    ("维护状态", "Maintenance"),
    ("参见核对", "See-also check"),
    ("本地数字证据影像", "Local digital-evidence image"),
    ("本页已打开；可返回当前核对", "This page is open; you may return to the current check"),
    ("档案开放目录", "Archives open catalog"),
    ("民俗资料网", "Folk-materials site"),
    ("旧报扫描库", "Old-paper scan library"),
    ("地质资料库", "Geology file library"),
    ("步骤 1", "Step 1"),
    ("步骤 2", "Step 2"),
    ("步骤 3", "Step 3"),
    ("已打开 · 重新查看", "Opened · view again"),
    ("打开来源", "Open source"),
    ("本项分屏", "Screens for this item"),
    ("已保存", "Saved"),
    ("等待前屏", "Waiting on previous"),
    ("核对工具栏", "Check toolbar"),
    ("当前业务步骤", "Current business steps"),
    ("面板 ", "Panel "),
    ("已记录", "Recorded"),
    ("处理状态工具栏", "Handling-status toolbar"),
    ("回单工具栏", "Return-form toolbar"),
    ("参见核对工具栏", "See-also toolbar"),
    ("论坛版面", "Forum boards"),
    ("论坛版面树", "Forum board tree"),
    ("开放目录栏目", "Open-catalog columns"),
    ("槐县图书馆地方文献室", "Huaixian Library local-literature room"),
    ("技术资料栏目", "Technical-file columns"),
    ("开放目录结果", "Open-catalog results"),
    ("游客", "Guest"),
    ("民俗资料栏目", "Folk holdings columns"),
    ("本站目录", "This-site catalog"),
    ("旧报扫描馆栏目", "Old-paper scan-library columns"),
    ("底片影像区", "Negatives image area"),
    ("报纸整版影像区", "Newspaper whole-page image area"),
    ("未著录", "Not described"),
    ("受控附件工具栏", "Controlled-attachment toolbar"),
    ("终点回执工具栏", "Endpoint-receipt toolbar"),
    ("精确路由清单中没有这个地址。公开记录不会使用宽前缀回退。",
     "This address is not on the exact-route list. Public records do not fall back to a wide prefix."),
    ("项目回执已标为已读。 ", "Project receipt marked read. "),
    ("本机复核会话已清除；公开世界数据没有改变。 ",
     "Local QC session cleared. Public world data did not change. "),
    ("每个工作面板的可见来源清单。来源只控制会话CTA，不是完成资格；每个问题的",
     "Visible source list for each work panel. Sources control session CTAs, not completion. Each question's"),
    ("correct anchor均显式引用本面板来源，测试据此检查没有隐藏常识答案。",
     "correct anchor cites this panel's sources; tests use that to check there is no hidden common-sense answer."),
    ("1.74—2.02米", "1.74—2.02 m"),
    ("1.61—1.88米", "1.61—1.88 m"),
    ("当前", "Current"),
]


def protect_svg(text: str) -> tuple[str, list[str]]:
    held: list[str] = []

    def keep(m: re.Match[str]) -> str:
        held.append(m.group(0))
        return f"__SVG_{len(held)-1}__"

    return SVG_RE.sub(keep, text), held


def restore_svg(text: str, held: list[str]) -> str:
    for i, blob in enumerate(held):
        text = text.replace(f"__SVG_{i}__", blob)
    return text


def protect_aliases(text: str) -> tuple[str, str]:
    m = re.search(r"  const searchKeywords = Object\.freeze\(\[[\s\S]*?\]\);", text)
    if not m:
        raise SystemExit("searchKeywords block not found")
    token = "___SEARCH_KEYWORDS_BLOCK___"
    return text[: m.start()] + token + text[m.end() :], m.group(0)


def longest_replace(text: str, pairs: list[tuple[str, str]]) -> str:
    pairs = sorted(((a, b) for a, b in pairs if a and a != b), key=lambda x: len(x[0]), reverse=True)
    for zh, en in pairs:
        if zh in text:
            text = text.replace(zh, en)
    return text


def structural(text: str) -> str:
    text = text.replace('<html lang="zh-CN">', '<html lang="en">', 1)
    text = text.replace(
        'content="槐县历史专卷数字化复核"',
        'content="Huaixian historical special-file digital QC"',
        1,
    )
    text = text.replace(
        'content="《镇山契：第九位到访者》v0.3 离线中文网页档案复核原型。"',
        'content="Mountain-Garrison Compact: Ninth Visitor v0.3. Offline records-QC prototype."',
        1,
    )
    text = text.replace(
        "<title>镇山契：第九位到访者｜虚构可玩原型</title>",
        "<title>Mountain-Garrison Compact: Ninth Visitor | fictional playable prototype</title>",
        1,
    )
    text = text.replace(
        'storageKey: "zhenshan_webgame_v0_3_cn_state_v1"',
        'storageKey: "zhenshan_webgame_v0_3_en_state_v1"',
        1,
    )
    text = text.replace('toLocaleLowerCase("zh-CN")', 'toLocaleLowerCase("en")')
    if CLASSIFY_NEW.split("function classifyHanWord")[0] not in text:
        pass
    text = re.sub(
        r"  function classifyHanWord\(value\) \{[\s\S]*?return \{ ok: true, kind: \"ok\", query: raw, msg: \"\" \};\n  \}",
        lambda _: CLASSIFY_NEW,
        text,
        count=1,
    )
    if SEARCH_RECORDS_LOOKUP_OLD not in text:
        raise SystemExit("search lookup not found")
    text = text.replace(SEARCH_RECORDS_LOOKUP_OLD, SEARCH_RECORDS_LOOKUP_NEW, 1)
    text = text.replace(
        'message: "抱歉，没有找到与“" + q + "”相关的结果。换一个已读页上的词试试."',
        'message: "Sorry, no results related to “" + q + "”. Try another word from a page you already read."',
    )
    text = text.replace(
        'message: "抱歉，没有找到与“" + q + "”相关的结果。换一个已读页上的词试试。"',
        'message: "Sorry, no results related to “" + q + "”. Try another word from a page you already read."',
    )
    text = text.replace(
        'return { ok: true, siteId, query: q, kind: "hit", count: results.length, results: clone(results), message: "共有 " + results.length + " 项符合条件的结果。" };',
        'return { ok: true, siteId, query: q, kind: "hit", count: results.length, results: clone(results), message: results.length + " matching result(s)." };',
    )
    text = text.replace(
        'message: "没有这个站点。"',
        'message: "There is no such site."',
    )
    text = text.replace(
        'message: "此文件已被禁止访问。"',
        'message: "This file is forbidden."',
    )
    text = re.sub(
        r'(<input type="search"[^>]*?)(autocomplete="off")',
        r'\1maxlength="32" \2',
        text,
    )
    if 'content: "Handover line' not in text and 'content: "交接栏' in text:
        text = text.replace(
            'content: "交接栏：________________　日期：________";',
            'content: "Handover line: ________________  Date: ________";',
        )
    text = text.replace('content: "本轮回执";', 'content: "This-round receipt";')
    text = text.replace('content: "来源记录";', 'content: "Source record";')
    if CSS_ARTIFACT.strip() not in text:
        text = text.replace("</style>", CSS_ARTIFACT + "\n</style>", 1)
    # Handover artifact for 阿山 is injected after copy replace in special_html().
    return text


def special_html(text: str) -> str:
    old = "The first word is already on the sheet: send AShan into Huaishui Locals as a single token."
    new = (
        "The first word is already on the sheet: send <strong>AShan</strong> "
        '<span class="zh-artifact" lang="zh-Hans">阿山</span>'
        '<span class="artifact-translation">AShan</span> '
        "into Huaishui Locals as a single token."
    )
    if old in text:
        text = text.replace(old, new, 1)
    text = text.replace(
        '<span class="forum-avatar" aria-hidden="true">槐</span>',
        '<span class="forum-avatar zh-artifact" lang="zh-Hans" aria-hidden="true">槐</span>',
    )
    text = text.replace(
        '<span class="archive-seal" aria-hidden="true">HX</span>',
        '<span class="archive-seal zh-artifact" lang="zh-Hans" aria-hidden="true">槐档</span><span class="artifact-translation">HX Archives</span>',
    )
    # if still Chinese seal
    text = text.replace(
        '<span class="archive-seal" aria-hidden="true">槐档</span>',
        '<span class="archive-seal zh-artifact" lang="zh-Hans" aria-hidden="true">槐档</span><span class="artifact-translation">HX Archives</span>',
    )
    return text


def remap_option_names(text: str) -> str:
    # After copy replace, leftover Chinese name tokens in option arrays / correct arrays.
    for zh, en in NAME_VALUES:
        text = text.replace(f'"{zh}"', f'"{en}"')
        text = text.replace(f"eastName={zh}", f"eastName={en}")
        text = text.replace(f"westName={zh}", f"westName={en}")
        text = text.replace(f"northName={zh}", f"northName={en}")
    return text


def remaining_han(text: str) -> tuple[int, list[str]]:
    stripped = SVG_RE.sub("SVGDATA", text)
    # drop search keyword aliases (Chinese kept on purpose)
    stripped = re.sub(r"  const searchKeywords = Object\.freeze\(\[[\s\S]*?\]\);", "", stripped)
    # drop artifact spans
    stripped = re.sub(
        r'<span class="[^"]*zh-artifact[^"]*"[^>]*>[\s\S]*?</span>',
        "",
        stripped,
    )
    toks = sorted(set(re.findall(r"[\u4e00-\u9fff]+", stripped)), key=lambda x: (-len(x), x))
    total = sum(len(t) * stripped.count(t) for t in toks)
    return total, toks


def main() -> None:
    raw = HTML.read_text(encoding="utf-8")
    mapping = json.loads(MAP_PATH.read_text(encoding="utf-8"))
    if not isinstance(mapping, dict):
        raise SystemExit("en_map.json must be an object")

    text, svgs = protect_svg(raw)
    text, alias_block = protect_aliases(text)

    text = structural(text)

    pairs = list(mapping.items()) + list(EXTRA)
    text = longest_replace(text, pairs)
    text = remap_option_names(text)
    text = special_html(text)

    # restore aliases with English added
    text = text.replace("___SEARCH_KEYWORDS_BLOCK___", SEARCH_BLOCK_NEW)
    text = restore_svg(text, svgs)

    HTML.write_text(text, encoding="utf-8")
    chars, toks = remaining_han(text)
    report = ROOT / "_loc" / "remaining_han.txt"
    report.write_text(
        f"han_chars_outside_artifacts={chars}\ntokens={len(toks)}\n" + "\n".join(toks[:400]),
        encoding="utf-8",
    )
    print("wrote", HTML)
    print("remaining han chars", chars, "tokens", len(toks))
    print("sample", toks[:40])


if __name__ == "__main__":
    main()
